import type { ClassPlan, SessionAttendance, Student } from '../types';

const daysAgo = (days: number, hour: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
};

export const demoPlans: ClassPlan[] = [
  {
    id: 'core-control',
    title: 'Core & Control',
    intention: 'Steady from the center',
    level: 'intermediate',
    plannedDurationMinutes: 60,
    peakPose: 'Navasana',
    status: 'ready',
    isPublished: true,
    taughtCount: 3,
    latestAdjustment: 'Add a Forearm Plank option and reduce Chaturanga rounds',
    lastTaughtAt: new Date('2026-08-28T10:00:00Z'),
  },
  {
    id: 'hanumanasana-flow',
    title: 'Hanumanasana Flow',
    intention: 'Progress gradually',
    level: 'intermediate',
    plannedDurationMinutes: 75,
    peakPose: 'Hanumanasana',
    status: 'draft',
    isPublished: false,
    taughtCount: 1,
    latestAdjustment: 'Introduce blocks during peak-pose preparation',
    lastTaughtAt: new Date('2026-08-28T10:00:00Z'),
  },
  {
    id: 'gentle-balance',
    title: 'Gentle Balance',
    intention: 'Balance with ease',
    level: 'all_levels',
    plannedDurationMinutes: 45,
    peakPose: 'Tree Pose',
    status: 'taught',
    isPublished: true,
    taughtCount: 5,
    latestAdjustment: 'Keep the balance work spacious and unhurried',
    lastTaughtAt: new Date('2026-08-28T10:00:00Z'),
  },
  {
    id: 'morning-mobility',
    title: 'Morning Mobility',
    intention: 'Wake up with ease',
    level: 'beginner',
    plannedDurationMinutes: 45,
    peakPose: 'Low Lunge',
    status: 'ready',
    isPublished: true,
    taughtCount: 2,
    latestAdjustment: 'Add more time for shoulder circles',
    lastTaughtAt: new Date('2026-08-26T08:00:00Z'),
  },
  {
    id: 'twists-and-tiles',
    title: 'Twists and Tiles',
    intention: 'Create space through the spine',
    level: 'intermediate',
    plannedDurationMinutes: 60,
    peakPose: 'Parivrtta Ardha Chandrasana',
    status: 'draft',
    isPublished: false,
    taughtCount: 0,
    latestAdjustment: 'Refine the transition into revolved lunge',
    lastTaughtAt: new Date('2026-08-24T10:00:00Z'),
  },
  {
    id: 'slow-strength',
    title: 'Slow Strength',
    intention: 'Build steady support',
    level: 'intermediate',
    plannedDurationMinutes: 75,
    peakPose: 'Bakasana',
    status: 'ready',
    isPublished: true,
    taughtCount: 4,
    latestAdjustment: 'Offer a supported crow variation',
    lastTaughtAt: new Date('2026-08-22T10:00:00Z'),
  },
  {
    id: 'restorative-evening',
    title: 'Restorative Evening',
    intention: 'Settle the nervous system',
    level: 'all_levels',
    plannedDurationMinutes: 60,
    peakPose: 'Supported Bridge',
    status: 'taught',
    isPublished: true,
    taughtCount: 6,
    latestAdjustment: 'Keep the final rest unhurried',
    lastTaughtAt: new Date('2026-08-20T18:00:00Z'),
  },
  {
    id: 'hips-and-hamstrings',
    title: 'Hips and Hamstrings',
    intention: 'Move toward spaciousness',
    level: 'intermediate',
    plannedDurationMinutes: 75,
    peakPose: 'Hanumanasana',
    status: 'draft',
    isPublished: false,
    taughtCount: 1,
    latestAdjustment: 'Add a longer preparation sequence',
    lastTaughtAt: new Date('2026-08-18T10:00:00Z'),
  },
  {
    id: 'balance-foundations',
    title: 'Balance Foundations',
    intention: 'Find a steady center',
    level: 'beginner',
    plannedDurationMinutes: 45,
    peakPose: 'Vrksasana',
    status: 'ready',
    isPublished: true,
    taughtCount: 3,
    latestAdjustment: 'Use the wall for first attempts',
    lastTaughtAt: new Date('2026-08-16T08:00:00Z'),
  },
  {
    id: 'backbends-with-care',
    title: 'Backbends with Care',
    intention: 'Open the front body gradually',
    level: 'advanced',
    plannedDurationMinutes: 90,
    peakPose: 'Urdhva Dhanurasana',
    status: 'draft',
    isPublished: false,
    taughtCount: 0,
    latestAdjustment: 'Add an accessible bridge option',
    lastTaughtAt: new Date('2026-08-14T10:00:00Z'),
  },
  {
    id: 'lunch-reset',
    title: 'Lunch Reset',
    intention: 'Return to the breath',
    level: 'all_levels',
    plannedDurationMinutes: 30,
    peakPose: 'Cat Cow',
    status: 'taught',
    isPublished: true,
    taughtCount: 8,
    latestAdjustment: 'Keep the sequence simple and bright',
    lastTaughtAt: new Date('2026-08-12T12:00:00Z'),
  },
  {
    id: 'core-stability-lab',
    title: 'Core Stability Lab',
    intention: 'Connect movement to the center',
    level: 'advanced',
    plannedDurationMinutes: 60,
    peakPose: 'Forearm Stand',
    status: 'ready',
    isPublished: true,
    taughtCount: 2,
    latestAdjustment: 'Sequence the wrist preparation earlier',
    lastTaughtAt: new Date('2026-08-10T10:00:00Z'),
  },
  {
    id: 'moonlit-release',
    title: 'Moonlit Release',
    intention: 'Make room for rest',
    level: 'all_levels',
    plannedDurationMinutes: 45,
    peakPose: 'Supta Baddha Konasana',
    status: 'taught',
    isPublished: true,
    taughtCount: 7,
    latestAdjustment: 'Offer extra support under the knees',
    lastTaughtAt: new Date('2026-08-08T18:00:00Z'),
  },
];

export const demoStudents: Student[] = [
  {
    id: 'ann',
    displayName: 'Ann',
    note: 'Prefers clear, progressive instructions',
    status: 'active',
  },
  {
    id: 'mali',
    displayName: 'Mali',
    note: 'Practices consistently twice a week',
    status: 'active',
  },
];

export const demoAttendance: SessionAttendance[] = [
  {
    id: 'visit-ann',
    studentId: 'ann',
    studentName: 'Ann',
    classTitle: 'Core & Control',
    attendedAt: daysAgo(1, 10),
  },
  {
    id: 'visit-mali',
    studentId: 'mali',
    studentName: 'Mali',
    classTitle: 'Core & Control',
    attendedAt: daysAgo(1, 10),
  },
];
