import * as stylex from '@stylexjs/stylex';
import { boxShadow, colors, fontSize, radius, spacing } from './tokens.stylex';

export const appStyles = stylex.create({
  sidebar: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.shell,
    color: colors.background,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    overflow: 'visible',
    paddingBlock: spacing.md,
    paddingInline: spacing.sm,
    position: 'sticky',
    top: spacing.page,
    transitionDuration: '220ms',
    transitionProperty: 'width, box-shadow',
    transitionTimingFunction: 'cubic-bezier(.22, 1, .36, 1)',
    width: 88,
    '@media (max-width: 860px)': {
      paddingInline: spacing.sm,
      position: 'relative',
      zIndex: 5,
    },
  },
  sidebarBrand: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  sidebarLogo: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 54,
    width: 54,
  },
  sidebarNav: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.sm,
    width: '100%',
  },
  sidebarLink: {
    alignItems: 'center',
    borderRadius: radius.pill,
    color: colors.primary,
    display: 'flex',
    gap: spacing.sm,
    minHeight: 54,
    height: 54,
    width: 54,
    flexShrink: 0,
    padding: spacing.sm,
    position: 'relative',
    justifyContent: 'center',
    transitionDuration: '200ms',
    transitionProperty: 'background-color, color, transform, border-radius',
    transitionTimingFunction: 'cubic-bezier(.22, 1, .36, 1)',
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        backgroundColor: colors.secondaryMuted,
        borderRadius: radius.pill,
        color: colors.primary,
        transform: 'translateX(3px)',
      },
    },
    ':focus-visible': {
      backgroundColor: colors.primaryOverlayFocus,
      color: colors.background,
      outlineColor: colors.tertiary,
      outlineOffset: 3,
      outlineStyle: 'solid',
      outlineWidth: 2,
    },
    '@media (prefers-reduced-motion: reduce)': {
      transitionDuration: '0ms',
      ':hover': { transform: 'none' },
    },
  },
  sidebarLinkActive: {
    backgroundColor: colors.background,
    color: colors.primary,
    fontWeight: 800,
    borderRadius: radius.pill,
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        backgroundColor: colors.background,
        color: colors.primary,
        transform: 'translateX(3px)',
      },
    },
    ':focus-visible': { backgroundColor: colors.background, color: colors.primary },
  },
  sidebarIcon: { color: colors.onPrimaryMuted },
  sidebarIconActive: { color: colors.primary },
  sidebarBottom: {
    alignItems: 'start',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
    marginTop: 'auto',
    width: '100%',
  },
  sidebarHint: {
    color: colors.onPrimarySubtle,
    fontSize: fontSize.xs,
    paddingInline: spacing.sm,
    textAlign: 'left',
    margin: 0,
  },
  profileMenuWrapper: {
    marginBottom: 0,
    paddingBottom: 0,
    position: 'relative',
  },
  accountGreeting: {
    color: colors.text,
    fontSize: fontSize.sm,
    fontWeight: 700,
    whiteSpace: 'nowrap',
  },
  profileLink: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    border: 0,
    cursor: 'pointer',
    display: 'flex',
    font: 'inherit',
    gap: spacing.sm,
    outline: 'none',
    paddingBlock: spacing.xs,
    paddingInline: spacing.xs,
    borderRadius: radius.md,
    transitionDuration: '120ms',
    transitionProperty: 'background-color',
    transitionTimingFunction: 'ease-out',
  },
  profileCopy: {
    alignItems: 'flex-end',
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  profileSubtitle: {
    color: colors.accent,
    fontSize: fontSize.xs,
    fontWeight: 700,
  },
  profileAvatar: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.pill,
    color: colors.primary,
    display: 'flex',
    justifyContent: 'center',
    height: 52,
    width: 52,
  },
  moonDayIcon: {
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.pill,
    boxShadow: boxShadow.moonGlow,
  },
  sidebarProfileLink: {
    backgroundColor: colors.primaryOverlaySubtle,
    borderRadius: radius.md,
    justifyContent: 'space-between',
    paddingBlock: spacing.sm,
    paddingInline: spacing.sm,
    width: '100%',
    ':hover': { backgroundColor: colors.primaryOverlayHover },
  },
  sidebarProfileLinkCollapsed: {
    justifyContent: 'center',
    paddingInline: spacing.xs,
    width: 56,
  },
  sidebarProfileMenuWrapper: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
  },
  sidebarProfileCopy: {},
  sidebarProfileCopyCollapsed: { display: 'none' },
  sidebarDropdownContent: {
    boxSizing: 'border-box',
    maxWidth: 'calc(100vw - 24px)',
    overflowWrap: 'anywhere',
    width: 216,
  },
  sidebarAccountGreeting: { color: colors.background },
  sidebarProfileSubtitle: { color: colors.tertiary },
  sidebarProfileAvatar: {
    backgroundColor: colors.tertiary,
    color: colors.primary,
    height: 42,
    width: 42,
  },
  dropdownContent: {
    backgroundColor: colors.secondaryMuted,
    borderRadius: radius.md,
    boxShadow: boxShadow.md,
    maxWidth: 'calc(100vw - 24px)',
    padding: spacing.sm,
    transformOrigin: 'var(--radix-popover-content-transform-origin)',
    width: 216,
    zIndex: 50,
  },
  dropdownItem: {
    alignItems: 'center',
    appearance: 'none',
    borderRadius: radius.sm,
    borderStyle: 'none',
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: colors.primary,
    cursor: 'pointer',
    display: 'flex',
    fontSize: fontSize.sm,
    fontWeight: 700,
    gap: spacing.sm,
    outline: 'none',
    minHeight: 40,
    paddingBlock: spacing.xs,
    paddingInline: spacing.sm,
    textAlign: 'left',
    textDecoration: 'none',
    transitionDuration: '120ms',
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',
    width: '100%',
    ':hover': {
      backgroundColor: colors.surface,
      transform: 'translateX(2px)',
    },
    ':focus-visible': {
      backgroundColor: colors.surface,
      outlineColor: colors.accent,
      outlineOffset: -2,
      outlineStyle: 'solid',
      outlineWidth: 2,
    },
    '@media (prefers-reduced-motion: reduce)': {
      transitionDuration: '0ms',
      ':hover': { transform: 'none' },
    },
  },
  dropdownIcon: { color: colors.primary, flexShrink: 0 },
});
