import * as stylex from '@stylexjs/stylex';
import { boxShadow, colors, fontSize, fontWeight, radius, spacing } from './tokens.stylex';

export const appStyles = stylex.create({
  sidebar: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.shell,
    color: colors.secondaryMuted,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    overflow: 'visible',
    paddingBlock: spacing.md,
    paddingInline: spacing.sm,
    position: 'sticky',
    top: spacing.page,
    transitionDuration: '220ms',
    transitionProperty: 'width, box-shadow',
    transitionTimingFunction: 'cubic-bezier(.22, 1, .36, 1)',
    width: 88,
    '@media (max-width: 860px)': {
      paddingInline: spacing.sm,
      position: 'relative',
      zIndex: 5,
    },
  },
  sidebarBrand: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  sidebarLogo: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 54,
    width: 54,
  },
  sidebarNav: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.sm,
    width: '100%',
  },
  sidebarMenuItem: {
    height: 54,
    position: 'relative',
    width: 54,
  },
  sidebarLink: {
    alignItems: 'center',
    borderRadius: radius.pill,
    color: colors.secondaryMuted,
    display: 'flex',
    gap: spacing.sm,
    minHeight: 54,
    height: 54,
    width: 54,
    flexShrink: 0,
    padding: spacing.sm,
    position: 'relative',
    zIndex: 9999999,
    justifyContent: 'center',
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        backgroundColor: colors.secondaryMuted,
        borderRadius: radius.pill,
        color: colors.primary,
        transform: 'translateX(3px)',
      },
    },
    ':focus-visible': {
      backgroundColor: colors.secondaryMuted,
      color: colors.secondaryMuted,
      outlineColor: colors.tertiary,
      outlineOffset: 3,
      outlineStyle: 'solid',
      outlineWidth: 2,
    },
    '@media (prefers-reduced-motion: reduce)': {
      transitionDuration: '0ms',
      ':hover': { transform: 'none' },
    },
  },
  sidebarLinkActive: {
    backgroundColor: colors.secondaryMuted,
    color: colors.primary,
    fontWeight: fontWeight.bold,
    borderRadius: radius.pill,
    zIndex: 9999999,
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        backgroundColor: colors.secondaryMuted,
        color: colors.primary,
        transform: 'translateX(3px)',
      },
    },
    ':focus-visible': { backgroundColor: colors.secondaryMuted, color: colors.primary },
  },
  sidebarIcon: { color: 'inherit' },
  sidebarIconActive: { color: colors.primary },
  sidebarMenuLabel: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMuted,
    borderRadius: radius.pill,
    boxShadow: boxShadow.md,
    color: colors.primary,
    display: 'flex',
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    insetInlineStart: `calc(100% - ${spacing.md})`,
    minHeight: 55,
    opacity: 0,
    paddingInlineEnd: spacing.lg,
    paddingInlineStart: spacing.xxxl,
    pointerEvents: 'none',
    position: 'absolute',
    top: '50%',
    transform: 'translate(-32px, -50.5%)',
    visibility: 'hidden',
    whiteSpace: 'nowrap',
    zIndex: 99999,
  },
  sidebarMenuLabelVisible: {
    opacity: 1,
    visibility: 'visible',
  },
  sidebarBottom: {
    alignItems: 'start',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
    marginTop: 'auto',
    width: '100%',
  },
  sidebarHint: {
    color: colors.secondary,
    fontSize: fontSize.xs,
    paddingInline: spacing.sm,
    textAlign: 'left',
    margin: 0,
  },
  moonDayIcon: {
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.pill,
    boxShadow: boxShadow.moonGlow,
  },
});
