import * as stylex from '@stylexjs/stylex';
import { boxShadow, colors, fontSize, radius, spacing } from './tokens.stylex';

export const appStyles = stylex.create({
  sidebar: {
    position: 'sticky',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'visible',
    minHeight: 0,
    minWidth: 0,
    height: '100%',
    width: '100%',
    backgroundColor: 'transparent',
    paddingBlock: spacing.md,
    '@media (max-width: 860px)': {
      position: 'relative',
      zIndex: 5,
    },
  },
  sidebarBrand: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xl,
  },
  sidebarLogo: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 48,
    width: 48,
  },
  sidebarNav: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    gap: spacing.xs,
    paddingBlock: 0,
    width: 60,
  },
  sidebarConnector: {
    position: 'absolute',
    fill: colors.primary,
    insetInlineStart: 0,
    pointerEvents: 'none',
    width: 60,
    height: 64,
    top: 30,
    zIndex: 0,
  },
  sidebarMenuItem: {
    position: 'relative',
    height: 60,
    width: 60,
  },
  sidebarLink: {
    position: 'relative',
    display: 'flex',
    flexShrink: 0,
    justifyContent: 'center',
    alignItems: 'center',
    color: colors.secondaryMutedLight,
    backgroundColor: colors.primary,
    borderRadius: '50%',
    minHeight: 60,
    height: 60,
    width: 60,
    aspectRatio: '1 / 1',
    boxSizing: 'border-box',
    flexBasis: 60,
    padding: spacing.xs,
    transitionDuration: '160ms',
    transitionProperty: 'background-color, color',
    transitionTimingFunction: 'cubic-bezier(.22, 1, .36, 1)',
    zIndex: 1,
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': { color: colors.tertiary },
    },
    ':focus-visible': {
      backgroundColor: colors.primary,
      color: colors.tertiary,
      outlineColor: colors.tertiary,
      outlineOffset: 3,
      outlineStyle: 'solid',
      outlineWidth: 2,
    },
    '@media (prefers-reduced-motion: reduce)': {
      transitionDuration: '0ms',
    },
  },
  sidebarLinkActive: {
    backgroundColor: colors.primary,
    color: colors.tertiary,
    zIndex: 3,

    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        backgroundColor: colors.primary,
        color: colors.tertiary,
      },
    },

    ':focus-visible': { backgroundColor: colors.primary, color: colors.tertiary },
  },
  sidebarIcon: { color: 'inherit', position: 'relative', zIndex: 2 },
  sidebarBottom: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'start',
  },
  sidebarRemarkBottom: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    paddingInline: spacing.md,
    lineHeight: 1.5,
    letterSpacing: '0.08em',
  },
  sidebarProfileButton: {
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.pill,
    height: 60,
    width: 60,
    padding: 0,
    marginTop: spacing.sm,
    ':hover': {
      filter: 'none',
      transform: 'translateY(-1px)',
    },
  },
  sidebarUtilityButton: {
    backgroundColor: colors.pageBackground,
    borderRadius: radius.pill,
    height: 44,
    width: 60,
    padding: 0,
    ':hover': {
      filter: 'none',
      transform: 'translateY(-1px)',
    },
  },
  moonDayIcon: {
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.pill,
    boxShadow: boxShadow.moonGlow,
  },
});
