import * as stylex from '@stylexjs/stylex';
import { boxShadow, colors, fontSize, fontWeight, radius, spacing } from './tokens.stylex';

export const dashboardStyles = stylex.create({
  overviewGrid: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    marginBottom: spacing.grid,
    '@media (max-width: 900px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 520px)': { gridTemplateColumns: '1fr' },
  },
  overviewTwoColumn: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'minmax(0, 1.15fr) minmax(300px, .85fr)',
    marginBottom: spacing.grid,
    '@media (max-width: 900px)': { gridTemplateColumns: '1fr' },
  },
  overviewBottom: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'minmax(0, .85fr) minmax(0, 1.15fr)',
    '@media (max-width: 900px)': { gridTemplateColumns: '1fr' },
  },
  overviewCard: {
    backgroundColor: colors.background,
    borderColor: colors.secondaryMuted,
    borderRadius: radius.card,
    borderWidth: 1,
    boxShadow: boxShadow.subtle,
    padding: spacing.lg,
  },
  classStatusEmpty: {
    color: colors.textMuted,
    marginBlock: 0,
    paddingBlock: spacing.lg,
  },
  classSearch: {
    flex: '0 1 320px',

    maxWidth: 420,
    position: 'relative',
  },
  classSearchInput: { paddingInlineEnd: spacing.xl },
  classSearchClear: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    border: 0,
    borderStyle: 'none',
    boxShadow: 'none',
    color: colors.textMuted,
    cursor: 'pointer',
    display: 'inline-flex',
    justifyContent: 'center',
    padding: spacing.xs,
    position: 'absolute',
    right: spacing.xs,
    top: '50%',
    transform: 'translateY(-50%)',
    ':hover': { color: colors.primary },
    ':focus-visible': {
      borderRadius: radius.sm,
      outline: `2px solid ${colors.primary}`,
      outlineOffset: 1,
    },
  },
  classLibraryToolbar: {
    alignItems: 'flex-end',
    display: 'flex',
    gap: spacing.md,
    marginBottom: spacing.md,
    justifyContent: 'space-between',
    '@media (max-width: 720px)': {
      alignItems: 'stretch',
      flexDirection: 'column-reverse',
      gap: 0,
    },
  },
  classLibrarySection: {
    display: 'flex',
    flex: '1 1 auto',
    flexDirection: 'column',
    minHeight: 0,
  },
  classPlanList: {
    alignContent: 'start',
    flex: '1 1 auto',
    maxHeight: 'none',
    minHeight: 0,
  },
  overviewAccent: { backgroundColor: colors.accentMuted },
  overviewLavender: { backgroundColor: colors.secondaryMuted },
  previewHeader: {
    alignItems: 'flex-start',
    display: 'flex',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  kicker: {
    color: colors.accent,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: '.08em',
    marginBlock: 0,
    textTransform: 'uppercase',
  },
  viewAllLink: {
    alignItems: 'center',
    color: colors.primary,
    display: 'inline-flex',
    flexShrink: 0,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    gap: spacing.xs,
    minHeight: 40,
  },
  openPlanLink: {
    transitionDuration: '150ms',
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
    ':hover': { transform: 'translateX(4px)' },
    ':focus-visible': { transform: 'translateX(4px)' },
  },
  statYellow: { backgroundColor: colors.tertiaryMuted },
  statGreen: { backgroundColor: colors.healthyMuted },
  statPink: { backgroundColor: colors.accentMuted },
  statPurple: { backgroundColor: colors.secondaryMuted },
  statValueWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'end',
    alignItems: 'flex-end',
  },
  previewList: {
    display: 'grid',
    gap: spacing.sm,
    paddingRight: spacing.xs,
  },
  previewRow: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: radius.md,
    color: colors.text,
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '40px minmax(0, 1fr) auto',
    minHeight: 64,
    padding: spacing.sm,
    textDecoration: 'none',
    ':hover': { backgroundColor: colors.secondaryMuted },
  },
  previewCopy: { display: 'grid', gap: 3, minWidth: 0 },
  previewIcon: {
    alignItems: 'center',
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.md,
    color: colors.primary,
    display: 'flex',
    fontWeight: fontWeight.bold,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  planCount: { color: colors.textMuted, fontSize: fontSize.sm, marginBlock: `0 ${spacing.lg}` },
  planPreviewRow: {
    alignItems: 'center',
    borderBottomColor: 'rgb(70 51 102 / .12)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    color: colors.text,
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    minHeight: 58,
    textDecoration: 'none',
    ':last-child': { borderBottomWidth: 0 },
    ':hover': { color: colors.accent },
  },
  activityMetrics: {
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'repeat(3, 1fr)',
    marginBottom: spacing.lg,
  },
  activityPreview: {
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.md,
    color: colors.primary,
    display: 'grid',
    fontSize: fontSize.sm,
    gap: spacing.sm,
    padding: spacing.md,
    textDecoration: 'none',
  },
  activityBar: { accentColor: colors.healthy, height: 10, width: '100%' },
  noteRow: {
    alignItems: 'center',
    borderBottomColor: 'rgb(70 51 102 / .12)',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    color: colors.text,
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '40px minmax(0, 1fr) auto',
    minHeight: 64,
    textDecoration: 'none',
    ':last-child': { borderBottomWidth: 0 },
    ':hover': { color: colors.accent },
  },
  noteStatus: {
    color: colors.healthy,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: 'capitalize',
  },
  fullPlanList: {
    display: 'grid',
    gap: spacing.sm,
    listStyle: 'none',
    margin: 0,
    maxHeight: 'clamp(220px, 48dvh, 560px)',
    overflowY: 'auto',
    padding: 0,
    scrollbarColor: `${colors.secondary} transparent`,
    scrollbarWidth: 'thin',
  },
  fullPlanRow: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMuted,
    borderRadius: radius.md,
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: 'minmax(0, 1fr) auto auto',
    height: 84,
    padding: spacing.md,
    '@media (max-width: 640px)': { gridTemplateColumns: 'minmax(0, 1fr) auto' },
  },
  dashboardWelcome: {
    alignItems: 'flex-end',
    display: 'flex',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginBottom: spacing.lg,
    '@media (max-width: 560px)': { alignItems: 'flex-start', flexDirection: 'column' },
  },
  dashboardIntro: { color: colors.textMuted, maxWidth: 560 },
  statCard: {
    backgroundColor: colors.background,
    borderRadius: radius.card,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    padding: spacing.md,
  },
  statLabel: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: fontWeight.semibold,
    textTransform: 'uppercase',
  },
  statValue: {
    color: colors.primary,
    fontSize: 'clamp(2rem, 4vw, 3.25rem)',
    fontWeight: fontWeight.bold,
    lineHeight: 1,
  },
  statMeta: { color: colors.textMuted, fontSize: fontSize.xs },
  planList: {
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    '@media (max-width: 560px)': { gridTemplateColumns: '1fr' },
  },
  planCard: {
    backgroundColor: colors.background,
    borderColor: colors.primary,
    borderRadius: radius.card,
    borderStyle: 'solid',
    borderWidth: 2,
    display: 'grid',
    gap: spacing.md,
    minHeight: 286,
    padding: spacing.lg,
  },
  planTop: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  taughtMeta: { textAlign: 'end' },
  meta: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    fontSize: fontSize.sm,
    gap: spacing.sm,
  },
  actions: {
    alignItems: 'center',
    alignSelf: 'end',
    display: 'flex',
    flexWrap: 'wrap',
    marginTop: spacing.sm,
  },
  allPlans: {
    marginTop: 0,
    backgroundColor: colors.secondaryMuted,
    paddingInline: spacing.md,
    paddingBlock: spacing.xl,
    borderRadius: radius.card,
    boxShadow: boxShadow.subtle,
  },
  allClasses: {
    display: 'grid',
    gap: spacing.sm,
    listStyle: 'none',
    marginBlock: 0,
    padding: 0,
  },
  allClassRow: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderColor: colors.background,
    borderRadius: radius.md,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: 'minmax(0, 1fr) 120px 56px 48px',
    paddingBlock: spacing.md,
    paddingInline: spacing.md,
    '@media (max-width: 520px)': {
      alignItems: 'flex-start',
      flexDirection: 'column',
      gridTemplateColumns: '1fr',
    },
  },
  allClassInfo: { display: 'grid', gap: spacing.xs, minWidth: 0 },
  allClassStatus: { justifySelf: 'center' },
  allClassAction: { justifySelf: 'end' },
  allClassTitle: { color: colors.primary, fontWeight: fontWeight.bold },
  allClassMeta: { color: colors.textMuted, fontSize: fontSize.sm },
  adjustment: {
    backgroundColor: colors.accentMuted,
    borderLeftColor: colors.accent,
    borderLeftStyle: 'solid',
    borderLeftWidth: 3,
    borderRadius: radius.sm,
    display: 'grid',
    fontSize: fontSize.sm,
    gap: spacing.xs,
    lineHeight: 1.35,
    marginTop: 1,
    paddingBlock: 11,
    paddingInline: 12,
  },
  adjustmentTitle: { fontSize: fontSize.xs },
  attendance: { marginTop: 0 },
  summaryGrid: {
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    marginBlock: spacing.md,
    marginBottom: 28,
    '@media (max-width: 700px)': { gridTemplateColumns: '1fr' },
  },
  summaryCard: {
    borderRadius: radius.lg,
    display: 'flex',
    justifyContent: 'space-between',
    minHeight: 132,
    padding: spacing.lg,
  },
  summaryTop: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  summaryLabel: { color: colors.textMuted, fontSize: fontSize.sm },
  summaryCount: {
    color: colors.primary,
    fontSize: fontSize.heading,
    fontWeight: fontWeight.bold,
  },
  summaryNote: { color: colors.textMuted, fontSize: fontSize.xs },
  summaryIcon: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  summaryGreen: { backgroundColor: colors.healthyMuted },
  summaryPink: { backgroundColor: '#ffe0df' },
  summaryLavender: { backgroundColor: '#e9e1f3' },
  weeklyTimeline: {
    backgroundColor: colors.background,
    borderColor: colors.secondaryMuted,
    borderRadius: radius.lg,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: boxShadow.subtle,
    minWidth: 0,
    overflowX: 'auto',
  },
  weeklyAvatarLink: {
    borderRadius: radius.pill,
    display: 'inline-flex',
    textDecoration: 'none',
    ':focus-visible': {
      outlineColor: colors.accent,
      outlineOffset: 2,
      outlineStyle: 'solid',
      outlineWidth: 2,
    },
  },
  teachingBoardHeader: {
    alignItems: 'center',
    color: colors.primary,
    display: 'grid',
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    gridTemplateColumns: '72px repeat(7, minmax(130px, 1fr))',
    minWidth: 1000,
    padding: spacing.sm,
    textAlign: 'center',
  },
  teachingBoardGrid: {
    borderTopColor: colors.secondaryMuted,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'grid',
    gridTemplateColumns: '72px repeat(7, minmax(130px, 1fr))',
    minWidth: 1000,
  },
  teachingTimeColumn: {
    color: colors.textMuted,
    display: 'grid',
    fontSize: fontSize.xs,
    gridTemplateRows: 'repeat(12, 64px)',
    paddingTop: 0,
    textAlign: 'right',
  },
  teachingDayColumn: {
    backgroundColor: colors.secondaryMuted,
    display: 'grid',
    gridTemplateRows: 'repeat(12, 64px)',
    position: 'relative',
  },
  teachingGridCell: {
    backgroundColor: colors.background,
    borderBottomColor: colors.secondaryMuted,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    borderLeftColor: colors.secondaryMuted,
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
  },
  teachingSession: {
    alignContent: 'start',
    backgroundColor: colors.secondary,
    borderColor: colors.primary,
    borderRadius: radius.md,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: boxShadow.sm,
    display: 'grid',
    gap: 2,
    margin: spacing.xs,
    minHeight: 56,
    overflow: 'hidden',
    padding: spacing.sm,
    position: 'relative',
    zIndex: 1,
  },
  teachingStudents: {
    display: 'flex',
    gap: 2,
    marginTop: spacing.xs,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    display: 'grid',
    fontWeight: fontWeight.bold,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  publishButton: {
    borderRadius: radius.pill,
    justifySelf: 'center',
    minHeight: 32,
    padding: spacing.xs,
  },
  dialogOverlay: {
    backgroundColor: 'rgb(31 18 53 / 0.32)',
    inset: 0,
    position: 'fixed',
    zIndex: 100,
  },
  dialogContent: {
    backgroundColor: colors.background,
    borderColor: colors.primary,
    borderRadius: radius.lg,
    borderStyle: 'solid',
    borderWidth: 2,
    boxShadow: boxShadow.lg,
    left: '50%',
    maxWidth: 420,
    padding: spacing.lg,
    position: 'fixed',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    width: 'calc(100% - 32px)',
    zIndex: 101,
  },
  dialogTitle: {
    color: colors.primary,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
  },
  dialogDescription: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 1.5,
    marginBlock: spacing.md,
  },
  dialogActions: {
    display: 'flex',
    gap: spacing.sm,
    justifyContent: 'flex-end',
  },
});
