import * as stylex from '@stylexjs/stylex';
import { boxShadow, colors, fontSize, fontWeight, radius, spacing } from './tokens.stylex';

const yinYangOrbit = stylex.keyframes({
  from: { transform: 'rotate(0deg)' },
  to: { transform: 'rotate(360deg)' },
});

const yinYangBreathe = stylex.keyframes({
  '0%': {
    filter: 'drop-shadow(0 2px 4px rgb(70 51 102 / 0.12))',
    transform: 'scale(0.96)',
  },
  '50%': {
    filter: 'drop-shadow(0 5px 10px rgb(70 51 102 / 0.24))',
    transform: 'scale(1.05)',
  },
  '100%': {
    filter: 'drop-shadow(0 2px 4px rgb(70 51 102 / 0.12))',
    transform: 'scale(0.96)',
  },
});

const roleButtonBase = {
  alignItems: 'center',
  backgroundColor: colors.primary,
  border: 0,
  color: colors.background,
  cursor: 'pointer',
  display: 'inline-flex',
  flex: 1,
  fontFamily: 'inherit',
  fontSize: '13px',
  fontWeight: fontWeight.bold,
  justifyContent: 'center',
  minHeight: '48px',
  paddingBlock: spacing.sm,
  paddingInline: spacing.md,
  whiteSpace: 'nowrap',
  transition: 'filter 180ms ease, transform 180ms ease',
  ':hover': { filter: 'brightness(1.08)', transform: 'translateY(-1px)' },
};

export const landingStyles = stylex.create({
  page: {
    backgroundColor: colors.pageBackground,
    color: colors.text,
    height: '100dvh',
    overflow: 'hidden',
  },
  nav: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    minHeight: '64px',
    width: '100%',
    borderBottom: `1px solid ${colors.secondaryMuted}`,
    paddingBlock: spacing.sm,
    paddingInline: spacing.xl,
    zIndex: 5,
  },
  navBrand: {
    display: 'inline-flex',
    alignItems: 'center',
    color: colors.primary,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    letterSpacing: '-0.04em',
  },
  navBrandIcon: { color: colors.accent, flexShrink: 0 },
  navLinks: {
    alignItems: 'center',
    display: 'flex',
    gap: 'clamp(16px, 3vw, 40px)',
    '@media (max-width: 560px)': { display: 'none' },
  },
  navLink: {
    color: colors.primary,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: '0.04em',
    paddingBlock: spacing.xs,
    position: 'relative',
    ':hover': { color: colors.accent },
    ':focus-visible': {
      outline: `2px solid ${colors.accent}`,
      outlineOffset: '4px',
    },
  },
  navCta: {
    backgroundColor: colors.tertiary,
    borderRadius: radius.pill,
    paddingInline: spacing.md,
    paddingBlock: spacing.xs,
  },
  hero: {
    display: 'grid',
    gridTemplateColumns: '1.1fr 1fr',
    position: 'relative',
    height: '100%',
    width: '100%',
    marginBlock: 'auto',
    minHeight: 0,
    '@media (max-width: 900px)': {
      gridTemplateColumns: '1fr',
      gap: spacing.md,
      paddingBlock: spacing.md,
    },
  },
  leftSide: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: colors.pageBackground,
    backgroundImage: `radial-gradient(circle at 8% 0%, ${colors.tertiaryMuted} 0%, transparent 44%),
      radial-gradient(circle at 100% 0%, ${colors.secondaryMutedLight} 0%, transparent 100%),
      radial-gradient(circle at 50% 50%, ${colors.tertiary} 0%, transparent 60%),
      radial-gradient(circle at 0% 100%, ${colors.accentMuted} 0%, transparent 90%)`,
    height: '100%',
    width: '100%',
    position: 'relative',
    zIndex: 2,
    '@media (max-width: 900px)': { marginInline: 'auto', textAlign: 'center' },
  },
  leftContent: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    paddingLeft: spacing.landing,
    marginBlock: 'auto',
    position: 'relative',
    width: '100%',
    maxWidth: '760px',
  },
  title: {
    color: colors.primary,
    fontSize: 'clamp(46px, min(5.8vw, 7.6vh), 54px)',
    fontWeight: fontWeight.semibold,
    lineHeight: 0.97,
    margin: 0,
    position: 'relative',
    zIndex: 1,
    '@media (max-width: 560px)': { fontSize: 'clamp(38px, 11vw, 54px)' },
  },
  titleWord: {
    position: 'relative',
    zIndex: 2,
  },
  spacing: {
    paddingRight: spacing.md,
  },
  spacingBottom: {
    paddingBottom: spacing.xl,
  },
  together: {
    display: 'inline-block',
    lineHeight: 0.9,
    overflow: 'visible',
    paddingInline: spacing.sm,
    paddingBottom: spacing.md,
    backgroundColor: colors.tertiary,
    position: 'relative',
    verticalAlign: 'baseline',
    zIndex: 1,
  },
  titleScriptGroup: {
    display: 'inline-block',
    position: 'relative',
    zIndex: 6,
  },
  titleScript: {
    display: 'inline-block',
    position: 'relative',
    color: colors.accent,
    fontFamily: 'var(--font-oooh-baby), cursive',
    fontSize: '1.08em',
    fontWeight: 1000,
    letterSpacing: '0.05em',
    lineHeight: 1.05,
    marginTop: '-20px',
    transform: 'translateY(0.02em) rotate(-7deg)',
    zIndex: 6,
  },
  titleJourney: {
    display: 'inline-block',
    paddingBottom: '0.28em',
    position: 'relative',
  },
  titleBrand: {
    color: colors.primary,
    fontFamily: 'var(--font-commit-mono), ui-monospace, monospace',
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    letterSpacing: '0em',
    lineHeight: 1,
    position: 'absolute',
    right: '0.4em',
    top: 'calc(100% - 1em)',
    whiteSpace: 'nowrap',
    paddingInline: spacing.md,
    paddingBlock: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: colors.tertiary,
  },
  description: {
    color: colors.text,
    fontSize: 'clamp(16px, 1.5vw, 18px)',
    lineHeight: 1.55,
    width: '100%',
    marginTop: spacing.md,
    '@media (max-width: 900px)': { marginInline: 'auto' },
  },
  roleSelector: {
    display: 'flex',
    position: 'relative',
    gap: spacing.sm,
    width: '100%',
    '@media (max-width: 560px)': { flexDirection: 'column', gap: spacing.lg },
  },
  roleButtonBase,
  roleTeacherButton: {
    borderTopLeftRadius: radius.pill,
    borderBottomLeftRadius: radius.pill,
  },
  roleStudentButton: {
    borderTopRightRadius: radius.pill,
    borderBottomRightRadius: radius.pill,
  },
  roleOptionInput: {
    clipPath: 'inset(50%)',
    height: '1px',
    overflow: 'hidden',
    position: 'absolute',
    whiteSpace: 'nowrap',
    width: '1px',
  },
  roleButtonStudent: {
    backgroundColor: colors.tertiary,
    color: colors.primary,
    ':hover': { filter: 'brightness(1.04)' },
  },
  roleTeacherButtonActive: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    boxShadow: `inset 0 -4px 10px ${colors.secondary}`,
  },
  roleStudentButtonActive: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    boxShadow: `inset 0 -4px 20px ${colors.tertiaryMuted}`,
  },
  yinYangCenter: {
    position: 'absolute',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.secondaryMuted,
    border: `3px solid ${colors.secondaryMuted}`,
    borderRadius: '50%',
    boxShadow: boxShadow.md,
    left: '50%',
    top: '50%',
    height: '54px',
    width: '54px',
    pointerEvents: 'none',
    transform: 'translate(-50%, -50%)',
    zIndex: 2,
    '@media (max-width: 560px)': { height: '48px', width: '48px' },
  },
  orbit: {
    border: `1px solid ${colors.accent}`,
    borderRadius: '50%',
    height: '70px',
    opacity: 0.72,
    position: 'absolute',
    width: '70px',
    animationName: yinYangOrbit,
    animationDuration: '7s',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'linear',
    '@media (max-width: 560px)': { height: '62px', width: '62px' },
    '@media (prefers-reduced-motion: reduce)': { animationDuration: '0ms' },
  },
  orbitDot: {
    position: 'absolute',
    backgroundColor: colors.tertiary,
    boxShadow: `0 3px 8px ${colors.tertiaryMuted}`,
    border: `2px solid ${colors.background}`,
    borderRadius: '50%',
    transform: 'translateX(-50%)',
    top: '-5px',
    left: '50%',
    height: '10px',
    width: '10px',
  },
  orbitDotSecondary: {
    backgroundColor: colors.primary,
    boxShadow: `0 3px 8px ${colors.secondaryMutedLight}`,
    top: 'auto',
    bottom: '-4px',
    left: '50%',
  },
  yinYangMotion: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    animationDuration: '4.8s',
    animationIterationCount: 'infinite',
    animationName: yinYangBreathe,
    animationTimingFunction: 'ease-in-out',
    '@media (prefers-reduced-motion: reduce)': { animationDuration: '0ms' },
  },
  yinYangGraphic: {
    color: colors.primary,
    height: '30px',
    transform: 'rotate(0deg)',
    transition: 'transform 420ms cubic-bezier(0.16, 1, 0.3, 1)',
    width: '30px',
    '@media (prefers-reduced-motion: reduce)': { transitionDuration: '120ms' },
  },
  yinYangGraphicStudent: { transform: 'rotate(180deg)' },
  note: {
    color: colors.text,
    fontSize: fontSize.xs,
    marginBlock: '0',
    opacity: 0.72,
    '@media (max-width: 900px)': { marginInline: 'auto' },
  },
  rightSide: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    boxSizing: 'border-box',
    width: '100%',
    height: '100%',
    backgroundColor: colors.secondaryMutedLight,
    backgroundImage: `radial-gradient(circle at 8% 0%, ${colors.secondaryMutedLight} 0%, transparent 20%),
      radial-gradient(circle at 100% 0%, ${colors.secondary} 0%, transparent 44%),
      radial-gradient(circle at 92% 100%, ${colors.accentMuted} 0%, transparent 60%),
      radial-gradient(circle at 0% 100%, ${colors.secondaryMutedLight} 0%, transparent 20%)`,
    borderRadius: radius.md,
    margin: 'auto',
    paddingInline: spacing.landing,
  },
  signInEyebrow: {
    color: colors.accent,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: '0.08em',
    margin: 0,
    textTransform: 'uppercase',
  },
  signInTitle: {
    fontFamily: 'var(--font-oooh-baby), cursive',
    color: colors.primary,
    fontSize: fontSize.heading,
    marginBlock: spacing.xs,
  },
  signInDescription: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    marginBlock: spacing.sm,
  },
  signInForm: {
    display: 'grid',
    position: 'relative',
  },
  signInRole: {
    gap: spacing.sm,
    width: '100%',
  },
  signInFields: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: spacing.sm,
    borderRadius: radius.md,
    padding: spacing.xl,
  },
  signInButton: { gridColumn: '1 / -1', width: '100%' },
  socialDivider: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    marginBlock: spacing.lg,
    color: colors.primary,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    '::before': {
      backgroundColor: colors.tertiary,
      content: '""',
      flex: 1,
      height: '1.5px',
    },
    '::after': {
      backgroundColor: colors.tertiary,
      content: '""',
      flex: 1,
      height: '1.5px',
    },
  },

  socialButtons: {
    display: 'grid',
    gridTemplateColumns: '1fr',
  },
  socialButton: {
    backgroundColor: colors.background,
    borderColor: colors.secondary,
    color: colors.primary,
    width: '100%',
    paddingInline: spacing.sm,
    ':hover': { backgroundColor: colors.secondaryMutedLight, filter: 'none' },
    ':focus-visible': {
      outline: `2px solid ${colors.accent}`,
      outlineOffset: '2px',
    },
  },
  visual: {
    minHeight: 'clamp(210px, 27vh, 300px)',
    position: 'relative',
    '@media (max-width: 900px)': { display: 'none' },
  },
  orb: {
    position: 'absolute',
    backgroundColor: colors.tertiaryMuted,
    borderRadius: '50%',
    opacity: 0.82,
    left: '32%',
    top: '10%',
    width: 'clamp(450px, 40vw, 560px)',
    height: 'clamp(450px, 40vw, 560px)',
    pointerEvents: 'none',
    zIndex: -1,
    '@media (max-width: 900px)': {
      height: 'min(82vw, 500px)',
      left: '50%',
      top: '-2%',
      transform: 'translateX(-50%)',
      width: 'min(82vw, 500px)',
    },
  },
  panel: {
    backgroundColor: colors.primary,
    borderRadius: radius.card,
    boxShadow: boxShadow.lg,
    color: colors.background,
    left: '2%',
    padding: 'clamp(18px, 2vw, 28px)',
    position: 'absolute',
    top: '4%',
    transform: 'rotate(-3deg)',
    width: 'min(68%, 340px)',
    zIndex: 1,
    '@media (max-width: 900px)': { left: '5%', top: '10%' },
  },
  panelLabel: {
    color: colors.tertiary,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    letterSpacing: '0.12em',
    margin: 0,
    textTransform: 'uppercase',
  },
  panelTitle: {
    fontSize: fontSize.lg,
    lineHeight: 1.12,
    marginBlock: spacing.md,
  },
  panelLine: {
    backgroundColor: colors.secondary,
    borderRadius: radius.pill,
    height: '8px',
    marginTop: spacing.sm,
    width: '100%',
  },
  panelLineShort: { backgroundColor: colors.accent, width: '66%' },
  roleCard: {
    backgroundColor: colors.background,
    border: `1px solid ${colors.secondaryMuted}`,
    borderRadius: radius.card,
    bottom: 0,
    boxShadow: boxShadow.lg,
    padding: 'clamp(16px, 1.6vw, 22px)',
    position: 'absolute',
    right: '10%',
    width: 'min(66%, 300px)',
    zIndex: 2,
    '@media (max-width: 900px)': { bottom: '3%', right: '1%' },
  },
  roleHeader: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  roleDot: {
    backgroundColor: colors.accent,
    borderRadius: '50%',
    height: '12px',
    width: '12px',
  },
  roleTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: fontWeight.semibold,
    margin: 0,
  },
  roleText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 1.5,
    margin: 0,
  },
  arc: {
    border: `1px solid ${colors.secondary}`,
    borderRadius: '50%',
    bottom: '-40%',
    right: '0',
    opacity: 0.55,
    position: 'absolute',
    transform: 'rotate(-14deg)',
    height: '70%',
    width: '70%',
  },
  footer: {
    backgroundColor: colors.primary,
    color: colors.background,
    fontSize: fontSize.xs,
    paddingBlock: '12px',
    paddingInline: 'clamp(24px, 8vw, 150px)',
    textAlign: 'center',
  },
});
