import * as stylex from '@stylexjs/stylex';
import { colors, radius, spacing } from './tokens.stylex';

export const layoutStyles = stylex.create({
  appFrame: {
    display: 'grid',
    gridTemplateColumns: '72px minmax(0, 1fr)',
    backgroundColor: colors.pageBackground,
    height: '100dvh',
    minHeight: '100dvh',
    maxHeight: '100dvh',
    overflow: 'hidden',
    gap: spacing.sm,
    paddingLeft: spacing.sm,
    '@media (max-width: 640px)': {
      gridTemplateColumns: '72px minmax(0, 1fr)',
      padding: spacing.sm,
    },
  },
  main: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    minHeight: 0,
    minWidth: 0,
  },
  appHeader: {
    alignItems: 'center',
    display: 'flex',
    paddingBlock: spacing.page,
    paddingInline: spacing.page,
  },
  appHeaderTitle: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.sm,
  },
  appHeaderDivider: { color: colors.textMuted },
  appHeaderMoonDay: {
    alignItems: 'center',
    borderRadius: radius.pill,
    color: colors.primary,
    display: 'inline-flex',
    justifyContent: 'center',
    padding: spacing.xs,
  },
  contentShell: {
    backgroundColor: colors.background,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
  },
  contentArea: {
    flex: 1,
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    scrollbarColor: `${colors.secondary} transparent`,
    scrollbarWidth: 'thin',
  },
  row: { alignItems: 'center', display: 'flex', flexDirection: 'row', gap: spacing.sm },
  rowBetween: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  rowStart: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'flex-start',
  },
  rowEnd: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'flex-end',
  },
  column: { display: 'flex', flexDirection: 'column', gap: spacing.sm },
  columnEnd: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    alignItems: 'end',
  },
  columnCenter: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  center: { alignItems: 'center', display: 'flex', justifyContent: 'center' },
  wrap: { flexWrap: 'wrap' },
});
