import * as stylex from '@stylexjs/stylex';
import { boxShadow, colors, fontWeight, radius, spacing } from './tokens.stylex';

export const plannerStyles = stylex.create({
  planner: {
    display: 'grid',
    gap: '22px',
  },
  goalsSection: {
    display: 'grid',
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  goalsHeader: {
    alignItems: 'baseline',
    display: 'flex',
    justifyContent: 'space-between',
  },
  goalsTitle: {
    color: colors.primary,
    fontSize: '1.15rem',
    fontWeight: fontWeight.bold,
    marginBlock: 0,
  },
  goalsSummary: { color: colors.textMuted, fontSize: '0.82rem', marginBlock: 0 },
  goalsGrid: {
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    '@media (max-width: 980px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 560px)': { gridTemplateColumns: '1fr' },
  },
  goalCard: {
    alignItems: 'flex-start',
    backgroundColor: colors.secondaryMuted,
    borderColor: colors.secondary,
    borderRadius: radius.md,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: boxShadow.subtle,
    color: colors.text,
    cursor: 'pointer',
    display: 'flex',
    gap: spacing.sm,
    minWidth: 0,
    padding: spacing.md,
    position: 'relative',
    textAlign: 'left',
    width: '100%',
    ':hover': { borderColor: colors.primary },
    ':focus-visible': { outline: `3px solid ${colors.tertiary}`, outlineOffset: 2 },
  },
  goalCardCompleted: { borderColor: colors.healthy },
  goalCardReady: { borderColor: colors.healthy },
  goalIcon: {
    alignItems: 'center',
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.sm,
    color: colors.primary,
    display: 'inline-flex',
    flexShrink: 0,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  goalIconCompleted: { backgroundColor: colors.healthyMuted, color: colors.healthy },
  goalIconReady: { backgroundColor: colors.healthyMuted, color: colors.healthy },
  goalCopy: { display: 'grid', gap: 4, minWidth: 0 },
  goalTitleRow: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.xs,
    paddingInlineEnd: spacing.lg,
  },
  goalTitle: { color: colors.primary, fontSize: '0.9rem', fontWeight: fontWeight.bold },
  goalCheck: {
    alignItems: 'center',
    backgroundColor: colors.healthy,
    borderRadius: '50%',
    color: colors.background,
    display: 'inline-flex',
    height: 18,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing.md,
    top: spacing.md,
    width: 18,
  },
  goalDescription: { color: colors.textMuted, fontSize: '0.76rem', lineHeight: 1.3 },
  goalProgressText: { color: colors.primary, fontSize: '0.75rem', fontWeight: fontWeight.semibold },
  goalProgressTrack: {
    backgroundColor: colors.background,
    borderRadius: radius.pill,
    display: 'block',
    height: 6,
    overflow: 'hidden',
    width: '100%',
  },
  goalProgressBar: {
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    display: 'block',
    height: '100%',
    transitionDuration: '180ms',
    transitionProperty: 'width, background-color',
    transitionTimingFunction: 'ease-out',
    '@media (prefers-reduced-motion: reduce)': { transitionDuration: '0ms' },
  },
  goalProgressBarCompleted: { backgroundColor: colors.healthy },
  goalProgressBarReady: { backgroundColor: colors.healthy },
  goalStatus: { color: colors.textMuted, fontSize: '0.72rem', fontWeight: fontWeight.semibold },
  goalStatusCompleted: { color: colors.healthy },
  goalStatusReady: { color: colors.healthy },
  actionStatusGroup: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  saveActionGroup: { alignItems: 'end', display: 'grid', gap: spacing.xs, justifyItems: 'end' },
  classStatus: {
    alignItems: 'center',
    color: colors.textMuted,
    display: 'inline-flex',
    fontSize: '0.82rem',
    gap: spacing.xs,
  },
  sectionEditorHeader: { display: 'grid', gap: spacing.xs },
  sectionEditorTitle: {
    color: colors.primary,
    fontSize: '1.15rem',
    fontWeight: fontWeight.bold,
    marginBlock: 0,
  },
  sectionEditorDescription: { color: colors.textMuted, fontSize: '0.9rem', marginBlock: 0 },
  grid: {
    display: 'grid',
    columnGap: spacing.md,
    rowGap: '6px',
    gridTemplateColumns: 'repeat(2, 1fr)',
    '@media (max-width: 700px)': {
      gridTemplateColumns: '1fr',
    },
  },
  halfField: { gridColumn: '1' },
  secondHalfField: {
    gridColumn: '2',
    '@media (max-width: 700px)': { gridColumn: '1' },
  },
  startFieldset: {
    borderColor: colors.secondary,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: spacing.sm,
    margin: 0,
    padding: spacing.md,
  },
  startOptions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  startDescription: {
    color: colors.textMuted,
    fontSize: '0.82rem',
    marginBlock: `0 ${spacing.sm}`,
  },
  templateRow: {
    alignItems: 'center',
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    '@media (max-width: 520px)': { gridTemplateColumns: '1fr' },
  },
  creationSteps: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  creationStep: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.sm,
  },
  creationStepNumber: {
    alignItems: 'center',
    backgroundColor: colors.tertiary,
    borderRadius: '50%',
    color: colors.primary,
    display: 'inline-flex',
    flexShrink: 0,
    fontWeight: fontWeight.bold,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  creationStepText: { color: colors.textMuted, fontSize: '0.82rem', lineHeight: 1.25 },
  sectionHeader: {
    alignItems: 'end',
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'minmax(0, 1fr) 120px auto',
    '@media (max-width: 520px)': { gridTemplateColumns: '1fr' },
  },
  durationField: { display: 'grid', gap: spacing.xs },
  sectionNameField: { display: 'grid', gap: spacing.xs },
  sectionList: { display: 'grid', gap: spacing.md },
  emptySections: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMuted,
    borderColor: colors.secondary,
    borderStyle: 'dashed',
    borderRadius: radius.md,
    display: 'grid',
    gap: spacing.xs,
    justifyItems: 'center',
    padding: spacing.xl,
    textAlign: 'center',
  },
  emptySectionsTitle: {
    color: colors.primary,
    fontWeight: fontWeight.bold,
    marginBlock: 0,
  },
  emptySectionsDescription: {
    color: colors.textMuted,
    fontSize: '0.9rem',
    marginBlock: `0 ${spacing.sm}`,
  },
  sectionDivider: {
    backgroundColor: colors.tertiary,
    border: 0,
    borderStyle: 'none',
    borderWidth: 0,
    height: 1,
    marginBlock: spacing.xs,
    width: '100%',
  },
  timeSummary: { width: 'fit-content', display: 'flex', alignItems: 'center' },
  sectionTitle: {
    border: 0,
    borderBottomColor: colors.primary,
    borderBottomStyle: 'solid',
    borderBottomWidth: 2,
    fontSize: '1.1rem',
    fontWeight: fontWeight.bold,
    padding: spacing.sm,
    width: '100%',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.sm,
    transitionDuration: '200ms',
    transitionProperty: 'opacity, transform',
    transitionTimingFunction: 'cubic-bezier(.22, 1, .36, 1)',
  },
  itemDragging: {
    opacity: 1,
  },
  dragHandle: {
    display: 'inline-flex',
    flexShrink: 0,
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'grab',
    backgroundColor: 'transparent',
    color: colors.textMuted,
    borderStyle: 'none',
    border: 0,
    minHeight: 38,
    width: 28,
    margin: 0,
    padding: spacing.xs,
    touchAction: 'none',
    ':hover': { color: colors.primary },
    ':active': { cursor: 'grabbing' },
    ':focus-visible': {
      borderRadius: spacing.xs,
      outlineColor: colors.primary,
      outlineOffset: 2,
      outlineStyle: 'solid',
      outlineWidth: 2,
    },
  },
  itemInput: { flex: 1 },
  emptyIcon: {
    padding: spacing.lg,
  },
});
