import * as stylex from '@stylexjs/stylex';
import { boxShadow, colors, fontSize, radius, spacing } from './tokens.stylex';

export const scheduleStyles = stylex.create({
  page: { padding: `0 ${spacing.page} ${spacing.page}`, minWidth: 0 },
  head: {
    alignItems: 'flex-end',
    display: 'flex',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginBottom: spacing.lg,
    '@media (max-width: 640px)': { alignItems: 'flex-start', flexDirection: 'column' },
  },
  actions: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  summaryGrid: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    marginBottom: spacing.grid,
    '@media (max-width: 900px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 520px)': { gridTemplateColumns: '1fr 1fr' },
  },
  summaryCard: {
    borderRadius: radius.card,
    boxShadow: boxShadow.subtle,
    padding: spacing.md,
    minHeight: 112,
  },
  summaryLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: 800,
    letterSpacing: '.06em',
    textTransform: 'uppercase',
  },
  summaryValue: {
    color: colors.primary,
    display: 'block',
    fontSize: fontSize.xl,
    fontWeight: 800,
    marginTop: spacing.sm,
  },
  summaryYellow: { backgroundColor: colors.tertiaryMuted },
  summaryGreen: { backgroundColor: colors.healthyMuted },
  summaryPurple: { backgroundColor: colors.secondaryMuted },
  summaryPink: { backgroundColor: colors.accentSoft },
  filters: {
    alignItems: 'end',
    backgroundColor: colors.primarySoft,
    borderRadius: radius.card,
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.grid,
    padding: spacing.md,
  },
  filter: { display: 'grid', gap: spacing.xs, minWidth: 140, flex: '1 1 140px' },
  filterLabel: { color: colors.primary, fontSize: fontSize.xs, fontWeight: 800 },
  input: {
    backgroundColor: colors.background,
    borderColor: colors.secondary,
    borderRadius: radius.sm,
    borderStyle: 'solid',
    borderWidth: 1,
    color: colors.text,
    minHeight: 38,
    padding: `0 ${spacing.sm}`,
    width: '100%',
  },
  calendarCard: {
    backgroundColor: colors.background,
    borderColor: colors.secondaryMuted,
    borderRadius: radius.card,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: boxShadow.subtle,
    minHeight: 600,
    overflow: 'hidden',
    padding: spacing.md,
    '@media (max-width: 640px)': { minHeight: 520, padding: spacing.sm },
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgb(31 18 53 / .42)',
    display: 'flex',
    inset: 0,
    justifyContent: 'center',
    padding: spacing.md,
    position: 'fixed',
    zIndex: 20,
  },
  modal: {
    backgroundColor: colors.background,
    borderRadius: radius.card,
    boxShadow: boxShadow.lg,
    maxHeight: '90dvh',
    maxWidth: 560,
    overflowY: 'auto',
    padding: spacing.lg,
    width: '100%',
  },
  modalHead: {
    alignItems: 'flex-start',
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  formGrid: { display: 'grid', gap: spacing.md, gridTemplateColumns: '1fr 1fr' },
  formGridSpaced: { marginTop: spacing.sm },
  full: { gridColumn: '1 / -1' },
  field: { display: 'grid', gap: spacing.xs },
  fieldLabel: { color: colors.textMuted, fontSize: fontSize.sm, fontWeight: 700 },
  modalActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'space-between',
    marginTop: spacing.lg,
  },
  empty: {
    alignItems: 'center',
    color: colors.textMuted,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    justifyContent: 'center',
    minHeight: 360,
    textAlign: 'center',
  },
  error: {
    backgroundColor: colors.accentSoft,
    borderRadius: radius.md,
    color: colors.danger,
    marginBottom: spacing.md,
    padding: spacing.md,
  },
});
