import * as stylex from '@stylexjs/stylex';
import { colors, fontSize, fontWeight, radius, spacing } from './tokens.stylex';

export const studentsStyles = stylex.create({
  privacy: {
    fontSize: fontSize.sm,
    color: colors.primary,
    backgroundColor: colors.accentMuted,
    borderRadius: radius.md,
    padding: spacing.md,
    paddingInlineEnd: 'clamp(96px, 14vw, 180px)',
    position: 'relative',
  },
  privacyWatermark: {
    bottom: spacing.md,
    color: colors.accent,
    opacity: 0.22,
    pointerEvents: 'none',
    position: 'absolute',
    right: 'clamp(24px, 5vw, 64px)',
  },
  privacyList: { marginBottom: 0 },
  form: {
    backgroundColor: colors.background,
    padding: 'clamp(16px, 3vw, 28px)',
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgb(31 18 53 / .42)',
    display: 'flex',
    inset: 0,
    justifyContent: 'center',
    padding: spacing.md,
    position: 'fixed',
    zIndex: 20,
  },
  modal: {
    backgroundColor: colors.background,
    borderRadius: radius.card,
    boxShadow: '0 8px 20px rgb(31 18 53 / 0.18)',
    maxHeight: '90dvh',
    maxWidth: 960,
    overflowY: 'auto',
    width: '100%',
  },
  profileFormShell: {
    marginTop: 0,
  },
  profileForm: {
    backgroundColor: colors.background,
    maxWidth: 'none',
    width: '100%',
  },
  profileFormFields: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderStyle: 'none',
    borderWidth: 0,
    borderRadius: 0,
    boxShadow: 'none',
    padding: 0,
  },
  profileView: {
    display: 'grid',
    gap: spacing.lg,
    marginTop: spacing.lg,
    maxWidth: 'none',
  },
  profileViewGrid: {
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    '@media (max-width: 640px)': { gridTemplateColumns: '1fr' },
  },
  profileViewCard: {
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.md,
    padding: spacing.md,
  },
  profileViewCardWide: { gridColumn: '1 / -1' },
  profileViewLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    marginBlock: 0,
    textTransform: 'uppercase',
  },
  profileViewValue: {
    color: colors.primary,
    marginBlock: spacing.xs,
    whiteSpace: 'pre-wrap',
  },
  profileViewTags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  profileViewTag: {
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.pill,
    color: colors.primary,
    fontSize: fontSize.xs,
    paddingBlock: spacing.xs,
    paddingInline: spacing.sm,
  },
  modalHead: {
    alignItems: 'flex-start',
    display: 'flex',
    justifyContent: 'space-between',
    padding: 'clamp(16px, 3vw, 28px)',
    paddingBottom: 0,
  },
  modalForm: { border: 0, margin: 0, padding: 'clamp(16px, 3vw, 28px)' },
  modalPrivacy: { marginInline: 'clamp(16px, 3vw, 28px)' },
  section: {
    borderTopColor: colors.tertiary,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
  },
  sectionFirst: { borderTopWidth: 0, marginTop: 0, paddingTop: 0 },
  sectionTitle: {
    color: colors.primary,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    marginBlock: 0,
    marginBottom: spacing.md,
  },
  fieldGrid: {
    display: 'grid',
    marginTop: spacing.md,
    gap: spacing.sm,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    '@media (max-width: 640px)': { gridTemplateColumns: '1fr' },
  },
  fullField: { gridColumn: '1 / -1' },
  optionGrid: {
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    '@media (max-width: 640px)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  option: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMutedLight,
    borderColor: colors.secondary,
    borderRadius: radius.sm,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    gap: spacing.sm,
    minHeight: 44,
    paddingInline: spacing.sm,
  },
  error: { color: colors.danger, fontSize: fontSize.xs, marginBlock: 0 },
  success: {
    backgroundColor: colors.healthyMuted,
    borderRadius: radius.sm,
    color: colors.text,
    marginBlock: spacing.md,
    padding: spacing.md,
  },
  formActions: {
    display: 'flex',
    gap: spacing.md,
    justifyContent: 'flex-end',
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
    '@media (max-width: 640px)': { flexDirection: 'column-reverse' },
  },
});
