import * as stylex from '@stylexjs/stylex';
import { boxShadow, colors, fontSize, fontWeight, radius, spacing } from './tokens.stylex';

export const workshopStyles = stylex.create({
  toolbar: {
    alignItems: 'end',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  search: { flex: '1 1 280px', maxWidth: 420 },
  filters: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  filterLabel: { color: colors.textMuted, fontSize: fontSize.sm },
  list: { display: 'grid', gap: spacing.md, listStyle: 'none', margin: 0, padding: 0 },
  row: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderColor: colors.secondaryMuted,
    borderRadius: radius.card,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: boxShadow.subtle,
    color: colors.text,
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: 'minmax(0, 1fr) auto auto',
    padding: spacing.lg,
    textDecoration: 'none',
    transitionDuration: '150ms',
    transitionProperty: 'transform, border-color',
    transitionTimingFunction: 'ease-out',
    ':hover': { borderColor: colors.primary, transform: 'translateY(-2px)' },
    '@media (max-width: 640px)': { gridTemplateColumns: '1fr', alignItems: 'start' },
  },
  rowCopy: { display: 'grid', gap: spacing.xs, minWidth: 0 },
  title: { color: colors.primary, fontSize: fontSize.lg, fontWeight: fontWeight.bold },
  description: { color: colors.textMuted, fontSize: fontSize.sm, lineHeight: 1.5, maxWidth: 680 },
  meta: { color: colors.textMuted, display: 'flex', flexWrap: 'wrap', gap: spacing.sm, fontSize: fontSize.sm },
  metaStrong: { color: colors.primary, fontWeight: fontWeight.semibold },
  action: { color: colors.primary, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  formLayout: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'minmax(0, 1.2fr) minmax(280px, .8fr)',
    '@media (max-width: 880px)': { gridTemplateColumns: '1fr' },
  },
  formCard: {
    backgroundColor: colors.background,
    borderColor: colors.secondaryMuted,
    borderRadius: radius.card,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: boxShadow.subtle,
    padding: spacing.lg,
  },
  formSection: { display: 'grid', gap: spacing.md, marginBottom: spacing.xl },
  formSectionLast: { marginBottom: 0 },
  formSectionTitle: { color: colors.primary, fontSize: fontSize.lg, fontWeight: fontWeight.bold, margin: 0 },
  fieldGrid: { display: 'grid', gap: spacing.md, gridTemplateColumns: '1fr 1fr', '@media (max-width: 600px)': { gridTemplateColumns: '1fr' } },
  field: { display: 'grid', gap: spacing.xs },
  full: { gridColumn: '1 / -1' },
  label: { color: colors.primary, fontSize: fontSize.sm, fontWeight: fontWeight.semibold },
  helper: { color: colors.textMuted, fontSize: fontSize.xs, margin: 0 },
  summary: { display: 'grid', gap: spacing.sm },
  summaryRow: { alignItems: 'baseline', display: 'flex', gap: spacing.sm, justifyContent: 'space-between' },
  summaryLabel: { color: colors.textMuted, fontSize: fontSize.sm },
  summaryValue: { color: colors.primary, fontWeight: fontWeight.semibold, textAlign: 'right' },
  actions: { display: 'flex', flexWrap: 'wrap', gap: spacing.sm, justifyContent: 'space-between', marginTop: spacing.lg },
  error: { backgroundColor: colors.accentMuted, borderRadius: radius.md, color: colors.danger, padding: spacing.md },
});

