import * as stylex from '@stylexjs/stylex';
import { boxShadow, colors, fontSize, fontWeight, radius, spacing } from './tokens.stylex';

export const yogiDashboardStyles = stylex.create({
  appPage: {
    color: colors.text,
    minHeight: '100dvh',
  },
  shell: {
    '@media (max-width: 760px)': { borderRadius: 0, minHeight: '100dvh', paddingBottom: 80 },
  },
  topbar: {
    alignItems: 'center',
    borderBottomColor: colors.secondaryMuted,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: 'auto auto minmax(220px, 1fr) auto auto auto',
    minHeight: 84,
    paddingInline: spacing.lg,
    '@media (max-width: 1080px)': { gridTemplateColumns: 'auto 1fr auto auto auto' },
    '@media (max-width: 760px)': {
      gap: spacing.sm,
      gridTemplateColumns: 'minmax(0, 1fr) auto auto auto',
      paddingBlock: spacing.sm,
      paddingInline: spacing.md,
    },
  },
  brand: {
    alignItems: 'center',
    color: colors.primary,
    display: 'flex',
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    gap: spacing.sm,
    textDecoration: 'none',
    whiteSpace: 'nowrap',
  },
  brandCaption: {
    color: colors.textMuted,
    display: 'block',
    fontSize: fontSize.xs,
    fontWeight: fontWeight.normal,
    marginTop: 2,
    '@media (max-width: 760px)': { display: 'none' },
  },
  desktopNav: { '@media (max-width: 760px)': { display: 'none' } },
  mobileScheduleTrigger: {
    display: 'inline-flex',
  },
  headerSearch: {
    alignItems: 'center',
    color: colors.textMuted,
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    justifySelf: 'center',
    maxWidth: 440,
    width: '100%',
    '@media (max-width: 1080px)': { display: 'none' },
  },
  mobileSearch: {
    display: 'none',
    '@media (max-width: 760px)': {
      alignItems: 'center',
      color: colors.textMuted,
      display: 'grid',
      gap: spacing.sm,
      gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    },
  },
  profileButton: { whiteSpace: 'nowrap' },
  profileAvatar: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    color: colors.background,
    display: 'flex',
    fontSize: fontSize.xs,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  profileCopy: {
    alignItems: 'flex-start',
    display: 'flex',
    flexDirection: 'column',
    fontSize: fontSize.xs,
    '@media (max-width: 760px)': { display: 'none' },
  },
  workspace: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    minHeight: 'calc(100dvh - 140px)',
  },
  contentColumn: {
    display: 'grid',
    gap: spacing.xl,
    minWidth: 0,
    padding: spacing.lg,
    '@media (max-width: 760px)': { gap: spacing.lg, padding: spacing.md },
  },
  welcome: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.lg,
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(260px, 0.48fr)',
    minHeight: 146,
    overflow: 'hidden',
    paddingLeft: spacing.lg,
    '@media (max-width: 760px)': {
      gridTemplateColumns: '1fr',
      minHeight: 124,
      padding: spacing.lg,
    },
  },
  welcomeTitle: {
    color: colors.primary,
    fontSize: 'clamp(1.75rem, 3vw, 2.65rem)',
    letterSpacing: '-0.03em',
    lineHeight: 1.05,
    margin: 0,
  },
  welcomeCopy: { color: colors.textMuted, margin: `${spacing.sm} 0 0` },
  heroMedia: {
    alignSelf: 'stretch',
    backgroundImage:
      'url(https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=900&q=84)',
    backgroundPosition: 'center 38%',
    backgroundSize: 'cover',
    minHeight: 146,
    '@media (max-width: 760px)': { display: 'none' },
  },
  summaryGrid: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    '@media (max-width: 880px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
  },
  section: { minWidth: 0 },
  classGrid: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(230px, 100%), 1fr))',
  },
  classCard: {
    backgroundColor: colors.background,
    borderRadius: radius.lg,
    boxShadow: boxShadow.subtle,
    minWidth: 0,
    overflow: 'hidden',
  },
  classImage: {
    alignItems: 'flex-start',
    aspectRatio: '16 / 9',
    backgroundColor: colors.secondaryMuted,
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    display: 'flex',
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  classBody: { display: 'grid', gap: spacing.md, padding: spacing.md },
  classHeading: {
    alignItems: 'flex-start',
    display: 'flex',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  classTitle: { color: colors.primary, fontSize: fontSize.lg, margin: 0 },
  recommendationReason: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    margin: `${spacing.xs} 0 0`,
  },
  instructorAvatar: {
    alignItems: 'center',
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.pill,
    color: colors.primary,
    display: 'flex',
    flex: '0 0 auto',
    fontWeight: fontWeight.bold,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  meta: {
    alignItems: 'center',
    color: colors.textMuted,
    display: 'flex',
    flexWrap: 'wrap',
    fontSize: fontSize.xs,
    gap: spacing.md,
  },
  metaItem: { alignItems: 'center', display: 'inline-flex', gap: spacing.xs },
  bookingList: {
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    '@media (max-width: 700px)': { gridTemplateColumns: '1fr' },
  },
  bookingRow: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: radius.md,
    boxShadow: boxShadow.subtle,
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '40px minmax(0, 1fr) auto auto',
    minHeight: 72,
    padding: spacing.sm,
    '@media (max-width: 520px)': { gridTemplateColumns: '40px minmax(0, 1fr) auto' },
  },
  bookingIcon: {
    alignItems: 'center',
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.md,
    color: colors.primary,
    display: 'flex',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  bookingCopy: { display: 'grid', fontSize: fontSize.xs, gap: spacing.xs, minWidth: 0 },
  emptyState: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMutedLight,
    borderColor: colors.secondary,
    borderRadius: radius.lg,
    borderStyle: 'dashed',
    borderWidth: 1,
    color: colors.textMuted,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    justifyContent: 'center',
    minHeight: 220,
    padding: spacing.lg,
    textAlign: 'center',
  },
  scheduleRail: {
    alignContent: 'start',
    borderLeftColor: colors.secondaryMuted,
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    gap: spacing.md,
    padding: spacing.lg,
    display: 'none',
  },
  schedulePopover: {
    alignContent: 'start',
    backgroundColor: colors.background,
    borderColor: colors.secondaryMuted,
    borderRadius: radius.lg,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: boxShadow.subtle,
    display: 'grid',
    gap: spacing.md,
    maxHeight: 'min(80dvh, 680px)',
    maxWidth: 'calc(100vw - 32px)',
    overflowY: 'auto',
    padding: spacing.md,
    width: 400,
  },
  calendarHeader: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  calendarMonth: { color: colors.textMuted, fontSize: fontSize.sm },
  calendarTitle: { color: colors.primary, fontSize: fontSize.xl, margin: `${spacing.xs} 0 0` },
  weekdays: {
    color: colors.textMuted,
    display: 'grid',
    fontSize: fontSize.xs,
    gridTemplateColumns: 'repeat(7, 1fr)',
    textAlign: 'center',
  },
  monthGrid: {
    display: 'grid',
    gap: spacing.xs,
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
  },
  scheduleDivider: { backgroundColor: colors.secondaryMuted, height: 1 },
  scheduleList: { display: 'grid', gap: spacing.sm },
  scheduleRow: {
    alignItems: 'start',
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '48px minmax(0, 1fr)',
  },
  scheduleEvent: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.md,
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '40px minmax(0, 1fr) auto',
    minHeight: 64,
    padding: spacing.sm,
  },
  mobileNav: {
    display: 'none',
    '@media (max-width: 760px)': {
      alignItems: 'center',
      backgroundColor: colors.primary,
      bottom: spacing.sm,
      borderRadius: radius.pill,
      display: 'flex',
      height: 64,
      justifyContent: 'space-around',
      left: spacing.sm,
      paddingInline: spacing.md,
      position: 'fixed',
      right: spacing.sm,
      zIndex: 20,
    },
  },
  mobileNavLink: {
    alignItems: 'center',
    borderRadius: radius.pill,
    color: colors.secondaryMuted,
    display: 'flex',
    height: 44,
    justifyContent: 'center',
    width: 44,
    ':first-child': { backgroundColor: colors.secondaryMuted, color: colors.primary },
    ':focus-visible': { outline: `2px solid ${colors.tertiary}`, outlineOffset: 2 },
  },
});
