import * as stylex from '@stylexjs/stylex';
import { boxShadow, colors, fontSize, fontWeight, radius, spacing } from './tokens.stylex';

export const yogiDashboardStyles = stylex.create({
  appPage: {
    color: colors.text,
    minHeight: '100dvh',
  },
  shell: {
    '@media (max-width: 760px)': { borderRadius: 0, minHeight: '100dvh', paddingBottom: 80 },
  },
  // topbar: {
  //   alignItems: 'center',
  //   borderBottomColor: colors.secondaryMuted,
  //   borderBottomStyle: 'solid',
  //   borderBottomWidth: 1,
  //   display: 'grid',
  //   gap: spacing.md,
  //   gridTemplateColumns: 'auto auto minmax(220px, 1fr) auto auto auto',
  //   minHeight: 84,
  //   paddingInline: spacing.lg,
  //   '@media (max-width: 1080px)': { gridTemplateColumns: 'auto 1fr auto auto auto' },
  //   '@media (max-width: 760px)': {
  //     gap: spacing.sm,
  //     gridTemplateColumns: 'minmax(0, 1fr) auto auto auto',
  //     paddingBlock: spacing.sm,
  //     paddingInline: spacing.md,
  //   },
  // },
  // brand: {
  //   alignItems: 'center',
  //   color: colors.primary,
  //   display: 'flex',
  //   fontSize: fontSize.lg,
  //   fontWeight: fontWeight.bold,
  //   gap: spacing.sm,
  //   textDecoration: 'none',
  //   whiteSpace: 'nowrap',
  // },
  // brandCaption: {
  //   color: colors.textMuted,
  //   display: 'block',
  //   fontSize: fontSize.xs,
  //   fontWeight: fontWeight.normal,
  //   marginTop: 2,
  //   '@media (max-width: 760px)': { display: 'none' },
  // },
  // desktopNav: { '@media (max-width: 760px)': { display: 'none' } },
  calendarCustom: {
    paddingInlineEnd: 0,
    borderInlineEndWidth: 0,
  },
  // headerSearch: {
  //   alignItems: 'center',
  //   color: colors.textMuted,
  //   display: 'grid',
  //   gap: spacing.sm,
  //   gridTemplateColumns: 'auto minmax(0, 1fr) auto',
  //   justifySelf: 'center',
  //   maxWidth: 440,
  //   width: '100%',
  //   '@media (max-width: 1080px)': { display: 'none' },
  // },
  // mobileSearch: {
  //   display: 'none',
  //   '@media (max-width: 760px)': {
  //     alignItems: 'center',
  //     color: colors.textMuted,
  //     display: 'grid',
  //     gap: spacing.sm,
  //     gridTemplateColumns: 'auto minmax(0, 1fr) auto',
  //   },
  // },
  // profileButton: { whiteSpace: 'nowrap' },
  // profileAvatar: {
  //   alignItems: 'center',
  //   backgroundColor: colors.primary,
  //   borderRadius: radius.pill,
  //   color: colors.background,
  //   display: 'flex',
  //   fontSize: fontSize.xs,
  //   height: 34,
  //   justifyContent: 'center',
  //   width: 34,
  // },
  // profileCopy: {
  //   alignItems: 'flex-start',
  //   display: 'flex',
  //   flexDirection: 'column',
  //   fontSize: fontSize.xs,
  //   '@media (max-width: 760px)': { display: 'none' },
  // },
  workspace: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    minHeight: 'calc(100dvh - 140px)',
    borderTopLeftRadius: radius.lg,
  },
  contentColumn: {
    display: 'grid',
    gap: spacing.lg,
    minWidth: 0,
    padding: spacing.md,
    paddingInline: spacing.lg,
  },
  welcome: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    // backgroundColor: colors.pageBackground,
    overflow: 'hidden',
    padding: spacing.lg,
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  welcomeTitle: {
    color: colors.primary,
    letterSpacing: '-0.03em',
    lineHeight: 1.05,
    margin: 0,
  },
  summaryGrid: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    '@media (max-width: 880px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
  },
  section: { minWidth: 0 },
  classGrid: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(230px, 100%), 1fr))',
  },
  classCard: {
    backgroundColor: colors.background,
    borderRadius: radius.lg,
    boxShadow: boxShadow.subtle,
    minWidth: 0,
    overflow: 'hidden',
  },
  classImage: {
    alignItems: 'flex-start',
    aspectRatio: '16 / 9',
    backgroundColor: colors.secondaryMuted,
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    display: 'flex',
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  classBody: { display: 'grid', gap: spacing.md, padding: spacing.md },
  classHeading: {
    alignItems: 'flex-start',
    display: 'flex',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  classTitle: { color: colors.primary, fontSize: fontSize.lg, margin: 0 },
  recommendationReason: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    margin: `${spacing.xs} 0 0`,
  },
  instructorAvatar: {
    alignItems: 'center',
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.pill,
    color: colors.primary,
    display: 'flex',
    flex: '0 0 auto',
    fontWeight: fontWeight.bold,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  meta: {
    alignItems: 'center',
    color: colors.textMuted,
    display: 'flex',
    flexWrap: 'wrap',
    fontSize: fontSize.xs,
    gap: spacing.md,
  },
  metaItem: { alignItems: 'center', display: 'inline-flex', gap: spacing.xs },
  bookingList: {
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    '@media (max-width: 700px)': { gridTemplateColumns: '1fr' },
  },
  bookingRow: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: radius.md,
    boxShadow: boxShadow.subtle,
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '40px minmax(0, 1fr) auto auto',
    minHeight: 72,
    padding: spacing.sm,
    '@media (max-width: 520px)': { gridTemplateColumns: '40px minmax(0, 1fr) auto' },
  },
  bookingIcon: {
    alignItems: 'center',
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.md,
    color: colors.primary,
    display: 'flex',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  bookingCopy: { display: 'grid', fontSize: fontSize.xs, gap: spacing.xs, minWidth: 0 },
  emptyState: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMutedLight,
    borderColor: colors.secondary,
    borderRadius: radius.lg,
    borderStyle: 'dashed',
    borderWidth: 1,
    color: colors.textMuted,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    justifyContent: 'center',
    minHeight: 220,
    padding: spacing.lg,
    textAlign: 'center',
  },
  scheduleRail: {
    alignContent: 'start',
    borderLeftColor: colors.secondaryMuted,
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    gap: spacing.md,
    padding: spacing.lg,
    display: 'none',
  },
  schedulePopover: {
    alignContent: 'start',
    backgroundColor: colors.background,
    borderColor: colors.secondaryMuted,
    borderRadius: radius.lg,
    borderStyle: 'solid',
    borderWidth: 1,
    boxShadow: boxShadow.subtle,
    display: 'grid',
    gap: spacing.md,
    maxHeight: 'min(80dvh, 680px)',
    maxWidth: 'calc(100vw - 32px)',
    overflowY: 'auto',
    padding: spacing.md,
    width: 400,
  },
  calendarHeader: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  calendarMonth: { color: colors.textMuted, fontSize: fontSize.sm },
  calendarTitle: { color: colors.primary, fontSize: fontSize.xl, margin: `${spacing.xs} 0 0` },
  weekdays: {
    color: colors.textMuted,
    display: 'grid',
    fontSize: fontSize.xs,
    gridTemplateColumns: 'repeat(7, 1fr)',
    textAlign: 'center',
  },
  monthGrid: {
    display: 'grid',
    gap: spacing.xs,
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
  },
  scheduleDivider: { backgroundColor: colors.secondaryMuted, height: 1 },
  scheduleList: { display: 'grid', gap: spacing.sm },
  scheduleRow: {
    alignItems: 'start',
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '48px minmax(0, 1fr)',
  },
  scheduleEvent: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.md,
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '40px minmax(0, 1fr) auto',
    minHeight: 64,
    padding: spacing.sm,
  },
  welcomeActions: { alignItems: 'center', display: 'flex', gap: spacing.xs },
  dashboardHero: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'minmax(0, 1.5fr) minmax(240px, .7fr)',
    '@media (max-width: 760px)': { gridTemplateColumns: '1fr' },
  },
  continueCard: {
    backgroundColor: colors.secondaryMuted,
    borderRadius: radius.card,
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(160px, .72fr)',
    minHeight: 280,
    overflow: 'hidden',
    '@media (max-width: 560px)': { gridTemplateColumns: '1fr' },
  },
  continueCopy: {
    display: 'grid',
    alignContent: 'center',
    gap: spacing.md,
    padding: spacing.xl,
    '@media (max-width: 560px)': { padding: spacing.lg },
  },
  continueArt: {
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    minHeight: 220,
    '@media (max-width: 560px)': { minHeight: 150 },
  },
  heroTitle: {
    color: colors.primary,
    fontSize: 'clamp(26px, 3vw, 40px)',
    letterSpacing: '-.04em',
    lineHeight: 1,
    margin: 0,
  },
  heroDescription: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    lineHeight: 1.5,
    margin: 0,
    maxWidth: 420,
  },
  progressRow: {
    color: colors.textMuted,
    display: 'flex',
    fontSize: fontSize.xs,
    justifyContent: 'space-between',
  },
  progressTrack: {
    backgroundColor: colors.secondaryMuted,
    borderRadius: radius.pill,
    height: 8,
    overflow: 'hidden',
    width: '100%',
  },
  progressTrackFill: {
    backgroundColor: colors.accent,
    borderRadius: radius.pill,
    display: 'block',
    height: '100%',
  },
  metricsCard: {
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.card,
    display: 'grid',
    gap: spacing.lg,
    padding: spacing.lg,
    alignContent: 'start',
  },
  metricHeader: {
    alignItems: 'center',
    color: colors.primary,
    display: 'flex',
    fontWeight: fontWeight.bold,
    justifyContent: 'space-between',
  },
  metricGrid: { display: 'grid', gap: spacing.sm, gridTemplateColumns: 'repeat(3, 1fr)' },
  metricGridItem: { display: 'grid', gap: spacing.xs },
  metricGridValue: { color: colors.primary, fontSize: fontSize.xl, fontWeight: fontWeight.bold },
  metricGridLabel: { color: colors.textMuted, fontSize: fontSize.xs },
  streakNote: {
    alignItems: 'center',
    color: colors.primary,
    display: 'flex',
    fontSize: fontSize.xs,
    gap: spacing.xs,
    lineHeight: 1.4,
  },
  filterBar: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.md,
    justifyContent: 'space-between',
    marginBottom: spacing.md,
    '@media (max-width: 720px)': { alignItems: 'stretch', flexDirection: 'column' },
  },
  categoryTabs: { display: 'flex', flexWrap: 'wrap', gap: spacing.xs },
  searchWrap: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.pill,
    color: colors.textMuted,
    display: 'flex',
    gap: spacing.xs,
    paddingInline: spacing.md,
    width: 'min(100%, 240px)',
    '@media (max-width: 720px)': { width: '100%' },
  },
  searchInput: { backgroundColor: 'transparent', border: 0, minHeight: 42, paddingInline: 0 },
  twoColumnSection: {
    display: 'grid',
    gap: spacing.grid,
    gridTemplateColumns: 'minmax(0, 1.08fr) minmax(300px, .92fr)',
    '@media (max-width: 900px)': { gridTemplateColumns: '1fr' },
  },
  learningList: { display: 'grid', gap: spacing.sm },
  learningRow: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: radius.lg,
    boxShadow: boxShadow.subtle,
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '56px minmax(0, 1fr) auto auto',
    padding: spacing.sm,
  },
  learningThumb: {
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    borderRadius: radius.md,
    height: 56,
    width: 56,
  },
  learningCopy: { display: 'grid', gap: spacing.xs, minWidth: 0 },
  learningCopySpan: { color: colors.textMuted, fontSize: fontSize.xs },
  learningPercent: { color: colors.primary, fontSize: fontSize.sm },
  studyCraftCard: {
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.card,
    display: 'grid',
    gap: spacing.md,
    minHeight: '100%',
    padding: spacing.lg,
  },
  studyCraftHeader: { alignItems: 'flex-start', display: 'flex', justifyContent: 'space-between' },
  studyCraftKicker: {
    color: colors.textMuted,
    display: 'block',
    fontSize: fontSize.xs,
    marginBottom: spacing.xs,
  },
  studyCraftTitle: {
    color: colors.primary,
    fontSize: fontSize.xl,
    letterSpacing: '-.03em',
    margin: 0,
  },
  studyCraftVisual: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    minHeight: 92,
    position: 'relative',
  },
  studyCraftOrb: {
    alignItems: 'center',
    borderRadius: radius.pill,
    display: 'flex',
    height: 52,
    justifyContent: 'center',
    position: 'absolute',
    width: 52,
  },
  studyCraftOrbPrimary: {
    backgroundColor: colors.secondaryMuted,
    color: colors.primary,
    transform: 'translateX(-40px) rotate(-10deg)',
  },
  studyCraftOrbAccent: {
    backgroundColor: colors.accentMuted,
    color: colors.accent,
    transform: 'translate(28px, -18px) rotate(12deg)',
  },
  studyCraftOrbSecondary: {
    backgroundColor: colors.healthyMuted,
    color: colors.healthy,
    transform: 'translate(28px, 24px) rotate(-8deg)',
  },
  studyCraftPlus: {
    color: colors.primary,
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    transform: 'translate(2px, 2px)',
  },
  studyCraftSummary: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  studyCraftSummaryCopy: { display: 'grid', gap: spacing.xs },
  studyCraftSummaryMeta: { color: colors.textMuted, fontSize: fontSize.xs },
  studyCraftProgress: {
    backgroundColor: colors.background,
    borderRadius: radius.pill,
    height: 8,
    overflow: 'hidden',
  },
  studyCraftPlanList: {
    backgroundColor: colors.background,
    borderRadius: radius.lg,
    display: 'grid',
    gap: spacing.sm,
    padding: spacing.md,
  },
  planCard: {
    backgroundColor: colors.background,
    borderRadius: radius.lg,
    boxShadow: boxShadow.subtle,
    display: 'grid',
    gap: spacing.sm,
    padding: spacing.md,
  },
  planHeader: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    paddingBottom: spacing.xs,
  },
  planHeaderSpan: {
    alignItems: 'center',
    color: colors.primary,
    display: 'inline-flex',
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    gap: spacing.xs,
  },
  planRow: {
    alignItems: 'center',
    borderTopColor: colors.secondaryMuted,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '24px minmax(0, 1fr) auto',
    paddingBlock: spacing.sm,
  },
  planRowCopy: { display: 'grid', gap: spacing.xs, minWidth: 0 },
  planRowDetail: { color: colors.textMuted, fontSize: fontSize.xs },
  planCheck: {
    alignItems: 'center',
    borderColor: colors.secondary,
    borderRadius: radius.pill,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  planCheckDone: {
    alignItems: 'center',
    backgroundColor: colors.healthy,
    borderRadius: radius.pill,
    color: colors.background,
    display: 'flex',
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  savedSection: { paddingBottom: spacing.xl },
  savedList: {
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    '@media (max-width: 760px)': { gridTemplateColumns: '1fr' },
  },
  savedItem: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMutedLight,
    border: 0,
    borderRadius: radius.lg,
    color: colors.primary,
    cursor: 'pointer',
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '40px minmax(0, 1fr) auto',
    padding: spacing.sm,
    textAlign: 'left',
    ':hover': { backgroundColor: colors.secondaryMuted },
  },
  savedIcon: {
    alignItems: 'center',
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.md,
    display: 'flex',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  savedItemCopy: { display: 'grid', gap: 2, minWidth: 0 },
  mobileNav: {
    display: 'none',
    '@media (max-width: 760px)': {
      alignItems: 'center',
      backgroundColor: colors.primary,
      bottom: spacing.sm,
      borderRadius: radius.pill,
      display: 'flex',
      height: 64,
      justifyContent: 'space-around',
      left: spacing.sm,
      paddingInline: spacing.md,
      position: 'fixed',
      right: spacing.sm,
      zIndex: 20,
    },
  },
  mobileNavLink: {
    alignItems: 'center',
    borderRadius: radius.pill,
    color: colors.secondaryMuted,
    display: 'flex',
    height: 44,
    justifyContent: 'center',
    width: 44,
    ':first-child': { backgroundColor: colors.secondaryMuted, color: colors.primary },
    ':focus-visible': { outline: `2px solid ${colors.tertiary}`, outlineOffset: 2 },
  },
});
