import * as stylex from '@stylexjs/stylex';
import { colors, fontSize, fontWeight, radius, spacing } from './tokens.stylex';

export const yogiStyles = stylex.create({
  history: {
    display: 'grid',
    gap: spacing.md,
    marginBottom: spacing.xl,
  },

  yogiTabsList: {
    marginBottom: spacing.lg,
  },
  historyDashboard: {
    display: 'grid',
    gridTemplateColumns: 'minmax(240px, 1fr) minmax(0, 2fr)',
    gap: spacing.lg,
    alignItems: 'start',
    '@media (max-width: 980px)': { gridTemplateColumns: '1fr' },
  },
  historyDashboardAll: {
    gridTemplateColumns: 'minmax(0, 1fr)',
  },
  calendarPanel: {
    backgroundColor: colors.secondaryMutedLight,
    border: `1px solid ${colors.secondaryMuted}`,
    borderRadius: radius.md,
    display: 'grid',
    gap: spacing.md,
    minWidth: 0,
    padding: spacing.md,
    position: 'sticky',
    top: spacing.md,
    '@media (max-width: 980px)': { position: 'static' },
  },
  calendarHeader: {
    alignItems: 'start',
    display: 'flex',
    justifyContent: 'space-between',
  },
  calendarEyebrow: {
    alignItems: 'center',
    color: colors.textMuted,
    display: 'flex',
    fontSize: '12px',
    fontWeight: fontWeight.semibold,
    gap: spacing.xs,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  calendarNav: { display: 'flex', gap: spacing.xs },
  calendarWeekdays: {
    color: colors.textMuted,
    display: 'grid',
    fontSize: '12px',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    textAlign: 'center',
  },
  calendarGrid: {
    display: 'grid',
    gap: spacing.xs,
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
  },
  calendarDay: {
    display: 'grid',
    position: 'relative',
    alignItems: 'center',
    justifyItems: 'center',
    fontSize: fontSize.xs,
    fontFamily: 'inherit',
    gap: 2,
    minHeight: 42,
    backgroundColor: colors.background,
    color: colors.primary,
    border: '1px solid transparent',
    borderRadius: radius.sm,
    cursor: 'pointer',
    ':hover': {
      backgroundColor: colors.secondaryMuted,
      borderColor: 'transparent',
      color: colors.primary,
    },
    ':focus-visible': {
      outline: `2px solid ${colors.primary}`,
      outlineOffset: 1,
    },
  },
  calendarDayOutside: { color: colors.textMuted, opacity: 0.5 },
  calendarDayActive: {
    backgroundColor: colors.primary,
    color: colors.background,
  },
  calendarDayToday: {
    backgroundColor: colors.tertiaryMuted,
    color: colors.primary,
    padding: 0,
  },
  calendarDateNumber: { gridRow: 1 },
  calendarDayIndicator: {
    backgroundColor: colors.accent,
    borderRadius: radius.pill,
    gridRow: 2,
    height: 5,
    width: 5,
  },
  calendarHint: { color: colors.textMuted, fontSize: '12px', margin: 0 },
  historyMain: {
    display: 'grid',
    gap: spacing.md,
    minWidth: 0,
  },
  historyHeading: {
    alignItems: 'end',
    display: 'flex',
    gap: spacing.md,
    justifyContent: 'space-between',
    '@media (max-width: 640px)': {
      alignItems: 'start',
      flexDirection: 'column',
    },
  },
  historyFilters: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.xs,
    padding: spacing.sm,
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.md,
  },
  filterLabel: {
    color: colors.textMuted,
    fontSize: '13px',
    fontWeight: fontWeight.semibold,
    marginRight: spacing.xs,
  },
  classFilter: {
    backgroundColor: colors.background,
    border: `1px solid ${colors.secondaryMuted}`,
    borderRadius: radius.pill,
    color: colors.primary,
    fontFamily: 'inherit',
    paddingBlock: spacing.xs,
    paddingInline: spacing.sm,
  },
  customRange: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
    color: colors.primary,
    fontSize: '14px',
  },
  datePickerPanel: {
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.md,
    color: colors.primary,
    padding: spacing.sm,
  },
  weekToolbar: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'space-between',
    padding: spacing.sm,
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.card,
  },
  weekLabel: { color: colors.primary, marginInline: 'auto' },
  daySelector: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: spacing.sm,
  },
  dayScroller: {
    maxWidth: '100%',
    overflowX: 'auto',
    paddingBottom: spacing.xs,
  },
  dayButton: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMutedLight,
    border: 0,
    borderRadius: radius.md,
    color: colors.primary,
    cursor: 'pointer',
    display: 'grid',
    gap: spacing.xs,
    minWidth: 62,
    padding: spacing.sm,
    position: 'relative',
    ':hover': { backgroundColor: colors.secondaryMuted, color: colors.primary },
    ':focus-visible': {
      outline: `2px solid ${colors.primary}`,
      outlineOffset: 2,
    },
  },
  dayButtonActive: {
    backgroundColor: colors.primary,
    color: colors.background,
  },
  dayButtonToday: {
    backgroundColor: colors.tertiaryMuted,
    color: colors.primary,
  },
  dayIndicator: {
    backgroundColor: colors.accent,
    borderRadius: radius.pill,
    display: 'block',
    height: 6,
    justifySelf: 'center',
    width: 6,
  },
  selectedDayHeading: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  countPill: {
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.pill,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    color: colors.primary,
    paddingBlock: spacing.xs,
    paddingInline: spacing.md,
  },
  visitList: {
    display: 'grid',
    gap: spacing.md,
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  visitListItem: { display: 'block' },
  visitCard: {
    display: 'grid',
    position: 'relative',
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.secondaryMutedLight,
    transitionDuration: '150ms',
    transitionProperty: 'border-color, box-shadow, transform',
    ':hover': {
      transform: 'translateY(-1px)',
      cursor: 'pointer',
    },
  },
  visitTopline: {
    alignItems: 'start',
    display: 'flex',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  visitTime: {
    color: colors.textMuted,
    display: 'block',
    fontSize: fontSize.sm,
    marginBottom: spacing.xs,
  },
  visitDate: {
    color: colors.textMuted,
    display: 'block',
    fontSize: fontSize.sm,
    marginBottom: spacing.xs,
  },
  visitTitle: {
    fontWeight: fontWeight.bold,
    color: colors.primary,
    marginBlock: 0,
  },
  visitNote: { color: colors.textMuted, margin: 0 },
  visitSummary: { minWidth: 0 },
  noteToggle: {
    display: 'inline-flex',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: spacing.xs,
    border: 0,
    borderRadius: radius.pill,
    color: colors.primary,
    minHeight: 32,
    right: spacing.md,
    top: spacing.md,
    transitionDuration: '150ms',
    transitionProperty: 'background-color, transform',
  },
  noteToggleOpen: {
    transform: 'rotate(180deg)',
  },
  emptyState: {
    display: 'grid',
    justifyItems: 'center',
    alignItems: 'center',
    textAlign: 'center',
    gap: spacing.md,
    padding: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.secondaryMutedLight,
    color: colors.textMuted,
  },
  emptyStateStrong: { color: colors.primary },
  emptyStateButton: {
    backgroundColor: colors.primary,
    border: 0,
    borderRadius: radius.pill,
    color: colors.background,
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontWeight: fontWeight.semibold,
    marginTop: spacing.sm,
    paddingBlock: spacing.xs,
    paddingInline: spacing.md,
  },
  allHistory: { display: 'grid', gap: spacing.lg },
  allHistoryMeta: {
    alignItems: 'center',
    color: colors.textMuted,
    display: 'flex',
    justifyContent: 'space-between',
  },
  historyRow: { display: 'block' },
  historyRowCard: {
    alignItems: 'center',
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.md,
    display: 'flex',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.md,
    '@media (max-width: 640px)': {
      alignItems: 'start',
      flexDirection: 'column',
    },
  },
  filterButton: {
    backgroundColor: colors.background,
    border: 0,
    borderRadius: radius.pill,
    color: colors.primary,
    cursor: 'pointer',
    paddingBlock: spacing.xs,
    paddingInline: spacing.sm,
  },
  filterButtonActive: {
    backgroundColor: colors.primary,
    color: colors.background,
  },
  historyList: {
    display: 'grid',
    gap: spacing.sm,
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  historyItem: {
    backgroundColor: colors.secondaryMutedLight,
    borderColor: colors.secondaryMuted,
    borderRadius: radius.md,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'grid',
    gap: 0,
    overflow: 'hidden',
  },
  historyItemHeader: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  historyRowButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderStyle: 'none',
    borderWidth: 0,
    border: 0,
    color: colors.text,
    cursor: 'pointer',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: spacing.md,
    minHeight: 64,
    paddingBlock: spacing.sm,
    paddingInline: spacing.md,
    textAlign: 'start',
    width: '100%',
    ':hover': { backgroundColor: colors.secondaryMuted, color: colors.accent },
    ':focus-visible': {
      outline: `2px solid ${colors.primary}`,
      outlineOffset: -2,
    },
  },
  historyRowButtonActive: { backgroundColor: colors.secondaryMutedLight },
  historyChevron: {
    color: colors.primary,
    transitionDuration: '150ms',
    transitionProperty: 'transform',
    transitionTimingFunction: 'ease-out',
  },
  historyChevronOpen: { transform: 'rotate(180deg)' },
  historyEditor: {
    backgroundColor: colors.secondaryMutedLight,
    display: 'grid',
    gap: spacing.sm,
    padding: spacing.sm,
  },
  historyEditorActions: { display: 'flex', justifyContent: 'flex-end' },
  historyClassInfo: { display: 'grid', gap: spacing.xs, justifyItems: 'start' },
  historyClassTitle: { color: colors.primary, fontWeight: fontWeight.bold },
  historyLevel: {
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.pill,
    color: colors.primary,
    fontSize: '12px',
    paddingBlock: spacing.xs,
    paddingInline: spacing.sm,
    width: 'fit-content',
  },
  historyDate: { color: colors.textMuted },
  historyNote: { display: 'grid', gap: spacing.xs },
  historyNoteLabel: {
    color: colors.primary,
    fontSize: '14px',
    fontWeight: fontWeight.semibold,
  },
  historyEmpty: {
    backgroundColor: colors.secondaryMutedLight,
    borderRadius: radius.md,
    color: colors.textMuted,
    margin: 0,
    padding: spacing.md,
  },
  list: {
    display: 'grid',
    gap: spacing.md,
    alignContent: 'start',
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  skeletonItem: {
    display: 'grid',
    gridTemplateColumns: '52px minmax(0, 1fr) auto auto',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.secondaryMutedLight,
    '@media (max-width: 640px)': {
      gridTemplateColumns: '40px minmax(0, 1fr)',
    },
  },
  skeletonAvatar: {
    height: 52,
    width: 52,
    borderRadius: radius.md,
    '@media (max-width: 640px)': {
      height: 40,
      width: 40,
    },
  },
  skeletonCopy: {
    display: 'grid',
    gap: spacing.xs,
    minWidth: 0,
  },
  skeletonTitle: {
    height: 18,
    width: 'min(240px, 70%)',
  },
  skeletonDescription: {
    height: 14,
    width: 'min(320px, 90%)',
  },
  skeletonBadge: {
    borderRadius: radius.pill,
    height: 28,
    width: 68,
    '@media (max-width: 640px)': {
      display: 'none',
    },
  },
  skeletonAction: {
    height: 18,
    width: 76,
    '@media (max-width: 640px)': {
      display: 'none',
    },
  },
  search: {
    maxWidth: 420,
    marginInlineStart: 'auto',
    position: 'relative',
    width: '100%',
    marginBottom: spacing.md,
  },
  searchInput: { paddingInlineEnd: spacing.xl },
  searchClear: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderStyle: 'none',
    border: 0,
    color: colors.textMuted,
    cursor: 'pointer',
    display: 'inline-flex',
    justifyContent: 'center',
    padding: spacing.xs,
    position: 'absolute',
    right: spacing.xs,
    top: '50%',
    transform: 'translateY(-50%)',
    ':hover': { color: colors.primary },
  },
  item: {
    display: 'grid',
    gridTemplateColumns: '52px minmax(0, 1fr) auto auto',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.secondaryMutedLight,
    color: colors.text,

    transitionDuration: '150ms',
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: 'ease-out',

    ':hover': {
      backgroundColor: colors.secondaryMuted,
      transform: 'translateX(2px)',
    },
    ':focus-visible': {
      outline: `2px solid ${colors.primary}`,
      outlineOffset: 2,
    },
    '@media (max-width: 640px)': {
      gridTemplateColumns: '40px minmax(0, 1fr) auto',
    },
  },
  avatar: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.tertiaryMuted,
    color: colors.primary,
    fontWeight: fontWeight.bold,
    height: 52,
    width: 52,
  },
  content: { minWidth: 0 },
  title: { color: colors.primary, marginBlock: 0 },
  description: {
    marginBlock: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  action: {
    color: colors.primary,
    display: 'inline-flex',
    transitionDuration: '150ms',
    transitionProperty: 'transform',
    ':hover': { transform: 'translateX(4px)' },
    '@media (max-width: 640px)': { display: 'none' },
  },
  today: {
    paddingInline: spacing.md,
    paddingBlock: 0,
    backgroundColor: colors.tertiaryMuted,
    borderRadius: radius.md,
    fontSize: fontSize.sm,
  },
});
